"""TalentReport entity — AI-generated insight about a candidate-job match."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from shared.domain import BaseEntity


class ReportType(str, Enum):
    CANDIDATE_SUMMARY = "candidate_summary"
    MATCH_ANALYSIS = "match_analysis"
    ACCOMMODATION_GUIDE = "accommodation_guide"
    TEAM_FIT = "team_fit"


class ReportStatus(str, Enum):
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass(eq=False)
class TalentReport(BaseEntity):
    """
    An AI-generated talent report.

    Reports are generated by the LLM (Ollama) based on anonymized
    candidate data. They never contain PII — only the NeuroVector24D
    dimensions and match context.
    """

    report_type: ReportType = ReportType.CANDIDATE_SUMMARY
    status: ReportStatus = ReportStatus.PENDING
    candidate_id: str = ""
    job_id: str | None = None
    content: str = ""
    prompt_used: str = ""
    model_name: str = ""
    tokens_used: int = 0

    def mark_generating(self) -> None:
        self.status = ReportStatus.GENERATING
        self.touch()

    def complete(self, content: str, model_name: str, tokens_used: int) -> None:
        if not content.strip():
            raise ReportError("Report content cannot be empty")
        self.content = content
        self.model_name = model_name
        self.tokens_used = tokens_used
        self.status = ReportStatus.COMPLETED
        self.touch()

    def fail(self, reason: str = "") -> None:
        self.content = f"Generation failed: {reason}" if reason else "Generation failed"
        self.status = ReportStatus.FAILED
        self.touch()

    def is_completed(self) -> bool:
        return self.status == ReportStatus.COMPLETED


class ReportError(Exception):
    pass
