// ═══════════════════════════════════════════════════════════════════
// CANDIDATOS NEURODIVERGENTES — 24 perfiles diversos
// Dominio: @seed.diversia.com (NUNCA mezclar con datos reales)
// Cada perfil refleja una idiosincrasia única y real
// Incluye perfiles de oficios manuales: construcción, mecánica,
// jardinería, artesanía, cocina, viveros
// ═══════════════════════════════════════════════════════════════════

export const candidateProfiles = [
    // ─── TDAH (3 perfiles) ───────────────────────────────────────
    {
        email: 'carlos.martinez@seed.diversia.com',
        firstName: 'Carlos',
        lastName: 'Martínez',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:flexible_schedule,noise_cancelling,task_chunking',
        experienceYears: 5,
        bio: 'Desarrollador frontend con TDAH. Mi hiperfoco me permite resolver bugs complejos en horas que a otros les llevan días. Trabajo mejor con plazos cortos y tareas bien definidas.',
        location: 'Madrid, Spain',
        skills: ['React', 'Next.js', 'TypeScript', 'CSS', 'Figma'],
        experience: [
            { title: 'Frontend Developer', company: 'StartupX', startYear: 2022, endYear: null, current: true, description: 'Desarrollo de SPA con React/Next.js' },
            { title: 'Junior Developer', company: 'WebAgency', startYear: 2020, endYear: 2022, current: false, description: 'Maquetación y desarrollo web' },
        ],
        education: [
            { degree: 'Grado en Ingeniería Informática', institution: 'Universidad Politécnica de Madrid', year: 2020, field: 'Informática' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 35000,
            salaryMax: 55000,
            locations: ['Madrid', 'Remote'],
            roles: ['Frontend Developer', 'Full-stack Developer'],
            industries: ['Technology', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-15T10:00:00Z',
            strengths: ['hyperfocus', 'creative_thinking', 'pattern_recognition', 'rapid_prototyping'],
            challenges: ['time_management', 'task_switching', 'sustained_attention_on_boring_tasks'],
            score: 78,
            technicalSkills: ['React', 'TypeScript', 'CSS'],
            softSkills: ['creativity', 'problem_solving', 'enthusiasm'],
            workStyle: { preferredHours: 'flexible', environment: 'quiet', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 15, matchesReceived: 4, applicationsSubmitted: 2 },
    },
    {
        email: 'lucia.fernandez@seed.diversia.com',
        firstName: 'Lucía',
        lastName: 'Fernández',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:pomodoro_timer,standing_desk,visual_reminders',
        experienceYears: 3,
        bio: 'Chef de repostería con TDAH. La cocina es mi espacio de hiperfoco perfecto: tareas manuales, creatividad y resultados inmediatos. Necesito listas claras y un ambiente donde pueda moverme.',
        location: 'Valencia, Spain',
        skills: ['Repostería creativa', 'Pastelería', 'Decoración', 'Gestión de cocina', 'APPCC'],
        experience: [
            { title: 'Chef de repostería', company: 'Dulce Hogar', startYear: 2023, endYear: null, current: true, description: 'Creación de postres y gestión de obrador' },
            { title: 'Ayudante de cocina', company: 'Restaurante El Faro', startYear: 2021, endYear: 2023, current: false, description: 'Apoyo en cocina y elaboración de postres' },
        ],
        education: [
            { degree: 'Técnico en Cocina y Gastronomía', institution: 'Escuela de Hostelería de Valencia', year: 2021, field: 'Hostelería' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 30000,
            locations: ['Valencia', 'Barcelona'],
            roles: ['Chef de repostería', 'Pastelera', 'Ayudante de cocina'],
            industries: ['Restauración', 'Alimentación'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-01T09:00:00Z',
            strengths: ['creativity', 'hands_on_work', 'sensory_precision', 'energy'],
            challenges: ['time_estimation', 'paperwork', 'following_long_recipes_without_visual_aid'],
            score: 72,
            technicalSkills: ['Repostería', 'APPCC', 'Decoración'],
            softSkills: ['creativity', 'teamwork', 'adaptability'],
            workStyle: { preferredHours: 'morning', environment: 'active', collaboration: 'in_person' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 8, matchesReceived: 2, applicationsSubmitted: 1 },
    },
    {
        email: 'diego.romero@seed.diversia.com',
        firstName: 'Diego',
        lastName: 'Romero',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:flexible_breaks,movement_allowed,clear_task_lists',
        experienceYears: 7,
        bio: 'Técnico de mantenimiento con TDAH. Resuelvo problemas mecánicos y eléctricos con rapidez porque mi mente conecta causas y efectos de forma no lineal. Necesito variedad de tareas.',
        location: 'Sevilla, Spain',
        skills: ['Electricidad', 'Fontanería', 'Climatización', 'Mantenimiento preventivo', 'PRL'],
        experience: [
            { title: 'Técnico de mantenimiento', company: 'Hotel Gran Vía', startYear: 2020, endYear: null, current: true, description: 'Mantenimiento integral de instalaciones' },
            { title: 'Electricista', company: 'InstalaSur', startYear: 2018, endYear: 2020, current: false, description: 'Instalaciones eléctricas y reparaciones' },
        ],
        education: [
            { degree: 'FP Grado Superior en Mantenimiento Electromecánico', institution: 'IES Politécnico de Sevilla', year: 2018, field: 'Mantenimiento' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 24000,
            salaryMax: 35000,
            locations: ['Sevilla', 'Málaga'],
            roles: ['Técnico de mantenimiento', 'Electricista', 'Operario'],
            industries: ['Servicios Generales', 'Hostelería', 'Logística'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-20T11:00:00Z',
            strengths: ['troubleshooting', 'hands_on_problem_solving', 'energy', 'multitasking_physical'],
            challenges: ['documentation', 'waiting', 'repetitive_tasks'],
            score: 74,
            technicalSkills: ['Electricidad', 'Climatización', 'PRL'],
            softSkills: ['initiative', 'adaptability', 'resourcefulness'],
            workStyle: { preferredHours: 'morning', environment: 'varied', collaboration: 'small_team' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 6, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── TEA / Autismo (3 perfiles) ─────────────────────────────
    {
        email: 'ana.garcia@seed.diversia.com',
        firstName: 'Ana',
        lastName: 'García',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:written_instructions,predictable_schedule,quiet_workspace,advance_notice_of_changes',
        experienceYears: 4,
        bio: 'Data scientist en el espectro autista. Mi capacidad para detectar patrones en grandes datasets es mi mayor fortaleza. Trabajo mejor con rutinas claras y comunicación escrita.',
        location: 'Barcelona, Spain',
        skills: ['Python', 'Data Science', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas'],
        experience: [
            { title: 'Data Analyst', company: 'DataFlow', startYear: 2023, endYear: null, current: true, description: 'ML pipelines y análisis de datos' },
            { title: 'Junior Data Scientist', company: 'AnalyticsCo', startYear: 2022, endYear: 2023, current: false, description: 'Modelos predictivos' },
        ],
        education: [
            { degree: 'MSc Data Science', institution: 'Universitat de Barcelona', year: 2022, field: 'Data Science' },
            { degree: 'Grado en Matemáticas', institution: 'Universitat de Barcelona', year: 2020, field: 'Matemáticas' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 40000,
            salaryMax: 60000,
            locations: ['Barcelona', 'Remote'],
            roles: ['Data Scientist', 'ML Engineer', 'Data Analyst'],
            industries: ['Technology', 'Healthcare', 'Finance'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-01T14:30:00Z',
            strengths: ['pattern_recognition', 'systematic_thinking', 'detail_orientation', 'data_analysis'],
            challenges: ['social_interactions', 'sensory_overload', 'unexpected_changes'],
            score: 88,
            technicalSkills: ['Python', 'SQL', 'TensorFlow'],
            softSkills: ['analytical_thinking', 'thoroughness', 'reliability'],
            workStyle: { preferredHours: 'fixed', environment: 'predictable', collaboration: 'structured' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 10, matchesReceived: 5, applicationsSubmitted: 1 },
    },
    {
        email: 'marcos.delgado@seed.diversia.com',
        firstName: 'Marcos',
        lastName: 'Delgado',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:structured_environment,visual_schedules,minimal_sensory_stimulation,clear_hierarchy',
        experienceYears: 6,
        bio: 'Técnico de control de calidad alimentaria. Mi atención al detalle extrema y mi capacidad para seguir protocolos al pie de la letra son ideales para garantizar la seguridad alimentaria.',
        location: 'Zaragoza, Spain',
        skills: ['Control de calidad', 'APPCC', 'ISO 22000', 'Análisis microbiológico', 'Trazabilidad', 'Documentación técnica'],
        experience: [
            { title: 'Técnico de calidad', company: 'AlimentosPuros S.A.', startYear: 2021, endYear: null, current: true, description: 'Control de calidad y auditorías internas' },
            { title: 'Auxiliar de laboratorio', company: 'LabAliment', startYear: 2019, endYear: 2021, current: false, description: 'Análisis microbiológicos de alimentos' },
        ],
        education: [
            { degree: 'Grado en Ciencia y Tecnología de los Alimentos', institution: 'Universidad de Zaragoza', year: 2019, field: 'Alimentación' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 28000,
            salaryMax: 38000,
            locations: ['Zaragoza', 'Barcelona'],
            roles: ['Técnico de calidad', 'Auditor alimentario', 'Analista de laboratorio'],
            industries: ['Alimentación', 'Salud', 'Farmacéutica'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-28T09:00:00Z',
            strengths: ['protocol_adherence', 'detail_orientation', 'systematic_documentation', 'pattern_detection'],
            challenges: ['team_meetings', 'sensory_sensitivity_to_smells', 'adapting_to_new_procedures'],
            score: 91,
            technicalSkills: ['APPCC', 'ISO 22000', 'Microbiología'],
            softSkills: ['precision', 'reliability', 'consistency'],
            workStyle: { preferredHours: 'fixed', environment: 'structured_lab', collaboration: 'minimal' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 7, matchesReceived: 3, applicationsSubmitted: 1 },
    },
    {
        email: 'irene.lopez@seed.diversia.com',
        firstName: 'Irene',
        lastName: 'López',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:written_communication,reduced_social_demands,consistent_routine,sensory_breaks',
        experienceYears: 2,
        bio: 'Operaria de almacén con TEA. Me apasiona el orden y la organización. Gestiono inventarios con precisión milimétrica y disfruto el trabajo metódico y repetitivo.',
        location: 'Bilbao, Spain',
        skills: ['Gestión de inventarios', 'Picking', 'WMS (SAP)', 'Organización de almacén', 'Carretilla elevadora'],
        experience: [
            { title: 'Operaria de almacén', company: 'LogiNorte', startYear: 2024, endYear: null, current: true, description: 'Picking, packing y gestión de inventario con WMS' },
        ],
        education: [
            { degree: 'FP Grado Medio en Actividades Comerciales', institution: 'IES Txurdinaga', year: 2023, field: 'Comercio' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 24000,
            locations: ['Bilbao', 'Vitoria'],
            roles: ['Operaria de almacén', 'Gestión de inventarios', 'Reponedora'],
            industries: ['Logística', 'Retail', 'Alimentación'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-10T08:00:00Z',
            strengths: ['organization', 'precision', 'routine_adherence', 'inventory_accuracy'],
            challenges: ['social_interaction', 'noisy_environments', 'task_interruptions'],
            score: 80,
            technicalSkills: ['WMS SAP', 'Carretilla', 'Inventarios'],
            softSkills: ['reliability', 'attention_to_detail', 'consistency'],
            workStyle: { preferredHours: 'fixed_morning', environment: 'organized', collaboration: 'independent' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Dislexia (2 perfiles) ──────────────────────────────────
    {
        email: 'pablo.herrera@seed.diversia.com',
        firstName: 'Pablo',
        lastName: 'Herrera',
        diagnoses: ['encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:text_to_speech,extra_time_reading,visual_aids,spell_checker',
        experienceYears: 8,
        bio: 'Diseñador gráfico con dislexia. Mi pensamiento visual tridimensional me permite crear diseños que otros no pueden imaginar. Necesito herramientas de corrección y tiempo extra para textos largos.',
        location: 'Madrid, Spain',
        skills: ['Adobe Photoshop', 'Illustrator', 'Figma', 'Diseño UX/UI', 'Branding', 'Fotografía'],
        experience: [
            { title: 'Senior Designer', company: 'BrandStudio', startYear: 2020, endYear: null, current: true, description: 'Dirección de arte y branding para startups' },
            { title: 'Graphic Designer', company: 'CreativeAgency', startYear: 2017, endYear: 2020, current: false, description: 'Diseño gráfico y web' },
        ],
        education: [
            { degree: 'Grado en Diseño Gráfico', institution: 'Escuela de Arte y Diseño de Madrid', year: 2017, field: 'Diseño' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 38000,
            salaryMax: 52000,
            locations: ['Madrid', 'Remote'],
            roles: ['Diseñador Gráfico', 'UX Designer', 'Director de Arte'],
            industries: ['Technology', 'Marketing', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-22T15:00:00Z',
            strengths: ['visual_thinking_3d', 'spatial_reasoning', 'creativity', 'big_picture_thinking'],
            challenges: ['reading_speed', 'spelling', 'written_documentation'],
            score: 82,
            technicalSkills: ['Photoshop', 'Figma', 'Illustrator'],
            softSkills: ['visual_communication', 'creativity', 'empathy'],
            workStyle: { preferredHours: 'flexible', environment: 'visual_rich', collaboration: 'visual_tools' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 11, matchesReceived: 4, applicationsSubmitted: 2 },
    },
    {
        email: 'nuria.santos@seed.diversia.com',
        firstName: 'Nuria',
        lastName: 'Santos',
        diagnoses: ['encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:audio_instructions,visual_schedules,dictation_software,reduced_written_reports',
        experienceYears: 4,
        bio: 'Educadora social con dislexia. Mi empatía y capacidad de conectar emocionalmente con las personas compensa con creces mi dificultad con los textos. Uso herramientas de dictado para informes.',
        location: 'Granada, Spain',
        skills: ['Trabajo social', 'Mediación', 'Educación no formal', 'Dinamización grupal', 'Intervención social'],
        experience: [
            { title: 'Educadora social', company: 'Fundación Abrigo', startYear: 2022, endYear: null, current: true, description: 'Acompañamiento a personas en riesgo de exclusión' },
            { title: 'Monitora de ocio', company: 'Asociación Viento', startYear: 2020, endYear: 2022, current: false, description: 'Actividades de ocio inclusivo para jóvenes' },
        ],
        education: [
            { degree: 'Grado en Educación Social', institution: 'Universidad de Granada', year: 2020, field: 'Educación Social' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 30000,
            locations: ['Granada', 'Málaga', 'Sevilla'],
            roles: ['Educadora social', 'Trabajadora social', 'Coordinadora de proyectos'],
            industries: ['ONG', 'Educación', 'Servicios Sociales'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-05T10:00:00Z',
            strengths: ['emotional_intelligence', 'verbal_communication', 'empathy', 'narrative_thinking'],
            challenges: ['written_reports', 'reading_long_documents', 'form_filling'],
            score: 76,
            technicalSkills: ['Mediación', 'Dinamización', 'Intervención social'],
            softSkills: ['empathy', 'communication', 'leadership'],
            workStyle: { preferredHours: 'morning', environment: 'social', collaboration: 'in_person' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Discalculia (1 perfil) ─────────────────────────────────
    {
        email: 'elena.ruiz@seed.diversia.com',
        firstName: 'Elena',
        lastName: 'Ruiz',
        diagnoses: ['encrypted:Discalculia'],
        accommodationsNeeded: 'encrypted:calculator_always,visual_math_aids,extra_time_for_numbers,no_mental_arithmetic',
        experienceYears: 5,
        bio: 'Periodista y copywriter con discalculia. Mi habilidad verbal es excepcional y compenso mi dificultad con números usando siempre calculadora. Redacto contenido persuasivo y creativo.',
        location: 'Barcelona, Spain',
        skills: ['Redacción', 'SEO', 'Copywriting', 'Redes sociales', 'WordPress', 'Storytelling'],
        experience: [
            { title: 'Content Manager', company: 'DigitalBrand', startYear: 2022, endYear: null, current: true, description: 'Estrategia de contenidos y copywriting' },
            { title: 'Redactora', company: 'Periódico Local', startYear: 2020, endYear: 2022, current: false, description: 'Redacción de noticias y reportajes' },
        ],
        education: [
            { degree: 'Grado en Periodismo', institution: 'Universitat Autònoma de Barcelona', year: 2020, field: 'Comunicación' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 28000,
            salaryMax: 40000,
            locations: ['Barcelona', 'Remote'],
            roles: ['Content Manager', 'Copywriter', 'Redactora'],
            industries: ['Marketing', 'Education', 'ONG'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-30T11:00:00Z',
            strengths: ['verbal_fluency', 'storytelling', 'conceptual_thinking', 'writing'],
            challenges: ['numerical_tasks', 'budgets', 'statistics', 'invoicing'],
            score: 73,
            technicalSkills: ['SEO', 'WordPress', 'Copywriting'],
            softSkills: ['communication', 'creativity', 'persuasion'],
            workStyle: { preferredHours: 'flexible', environment: 'creative', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 9, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── Dispraxia / TDC (1 perfil) ────────────────────────────
    {
        email: 'jorge.navarro@seed.diversia.com',
        firstName: 'Jorge',
        lastName: 'Navarro',
        diagnoses: ['encrypted:Dispraxia_TDC'],
        accommodationsNeeded: 'encrypted:ergonomic_equipment,voice_input,extra_time_writing,minimal_handwriting',
        experienceYears: 6,
        bio: 'Consultor de accesibilidad con dispraxia. Mi experiencia personal me da una perspectiva única para diseñar entornos accesibles. Uso dictado por voz y herramientas adaptadas.',
        location: 'Madrid, Spain',
        skills: ['Consultoría accesibilidad', 'WCAG 2.1', 'UX Research', 'Evaluación ergonómica', 'Normativa accesibilidad'],
        experience: [
            { title: 'Consultor de accesibilidad', company: 'AccesibleYA', startYear: 2021, endYear: null, current: true, description: 'Auditorías de accesibilidad web y física' },
            { title: 'UX Researcher', company: 'UserFirst', startYear: 2019, endYear: 2021, current: false, description: 'Investigación de experiencia de usuario' },
        ],
        education: [
            { degree: 'Máster en Interacción Persona-Ordenador', institution: 'Universidad Carlos III', year: 2019, field: 'HCI' },
            { degree: 'Grado en Psicología', institution: 'UNED', year: 2017, field: 'Psicología' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 35000,
            salaryMax: 48000,
            locations: ['Madrid', 'Remote'],
            roles: ['Consultor accesibilidad', 'UX Researcher', 'Especialista D&I'],
            industries: ['Technology', 'Consultoría', 'Educación'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-08T14:00:00Z',
            strengths: ['strategic_thinking', 'empathy', 'resilience', 'verbal_reasoning'],
            challenges: ['fine_motor_skills', 'handwriting', 'spatial_organization', 'physical_coordination'],
            score: 79,
            technicalSkills: ['WCAG', 'UX Research', 'Accesibilidad'],
            softSkills: ['empathy', 'strategic_thinking', 'advocacy'],
            workStyle: { preferredHours: 'flexible', environment: 'ergonomic', collaboration: 'video_calls' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 7, matchesReceived: 3, applicationsSubmitted: 1 },
    },

    // ─── Síndrome de Tourette (1 perfil) ────────────────────────
    {
        email: 'raul.castro@seed.diversia.com',
        firstName: 'Raúl',
        lastName: 'Castro',
        diagnoses: ['encrypted:Sindrome_Tourette'],
        accommodationsNeeded: 'encrypted:understanding_environment,breaks_when_needed,private_workspace_option,no_customer_facing_pressure',
        experienceYears: 4,
        bio: 'Programador backend con síndrome de Tourette. Mi determinación y enfoque intenso me permiten escribir código limpio y eficiente. Trabajo mejor en entornos comprensivos donde puedo tomar descansos.',
        location: 'Málaga, Spain',
        skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'AWS', 'Testing'],
        experience: [
            { title: 'Backend Developer', company: 'CloudOps', startYear: 2023, endYear: null, current: true, description: 'Microservicios con Spring Boot' },
            { title: 'Junior Developer', company: 'TechMálaga', startYear: 2021, endYear: 2023, current: false, description: 'Desarrollo Java y APIs REST' },
        ],
        education: [
            { degree: 'Grado en Ingeniería del Software', institution: 'Universidad de Málaga', year: 2021, field: 'Software' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 32000,
            salaryMax: 48000,
            locations: ['Málaga', 'Remote'],
            roles: ['Backend Developer', 'Full-stack Developer', 'DevOps'],
            industries: ['Technology', 'Finance'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-12T10:00:00Z',
            strengths: ['determination', 'intense_focus', 'clean_code', 'perseverance'],
            challenges: ['tic_management', 'public_speaking', 'high_pressure_situations'],
            score: 81,
            technicalSkills: ['Java', 'Spring Boot', 'Docker'],
            softSkills: ['determination', 'focus', 'resilience'],
            workStyle: { preferredHours: 'flexible', environment: 'private', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 3, applicationsSubmitted: 1 },
    },

    // ─── TPS (Procesamiento Sensorial) (1 perfil) ──────────────
    {
        email: 'clara.medina@seed.diversia.com',
        firstName: 'Clara',
        lastName: 'Medina',
        diagnoses: ['encrypted:TPS_Procesamiento_Sensorial'],
        accommodationsNeeded: 'encrypted:noise_cancelling,dim_lighting,scent_free_environment,sensory_breaks,no_open_office',
        experienceYears: 3,
        bio: 'Ilustradora y artista digital con TPS. Mi hipersensibilidad sensorial alimenta mi arte: percibo matices de color y textura que otros no ven. Necesito control sobre mi entorno sensorial.',
        location: 'Valencia, Spain',
        skills: ['Ilustración digital', 'Procreate', 'Adobe Creative Suite', 'Animación 2D', 'Storyboarding'],
        experience: [
            { title: 'Ilustradora freelance', company: 'Autónoma', startYear: 2023, endYear: null, current: true, description: 'Ilustración para editoriales y marcas' },
            { title: 'Artista junior', company: 'AnimaStudio', startYear: 2022, endYear: 2023, current: false, description: 'Animación 2D para publicidad' },
        ],
        education: [
            { degree: 'Grado en Bellas Artes', institution: 'Universidad Politécnica de Valencia', year: 2022, field: 'Arte' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 24000,
            salaryMax: 36000,
            locations: ['Valencia', 'Remote'],
            roles: ['Ilustradora', 'Artista digital', 'Animadora 2D'],
            industries: ['Marketing', 'Education', 'Entertainment'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-14T16:00:00Z',
            strengths: ['color_perception', 'texture_sensitivity', 'artistic_vision', 'detail_in_visual_work'],
            challenges: ['noisy_environments', 'strong_smells', 'fluorescent_lighting', 'crowds'],
            score: 77,
            technicalSkills: ['Procreate', 'Photoshop', 'Animación 2D'],
            softSkills: ['artistic_sensitivity', 'observation', 'patience'],
            workStyle: { preferredHours: 'flexible', environment: 'controlled_sensory', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 6, matchesReceived: 2, applicationsSubmitted: 0 },
    },

    // ─── Altas Capacidades / Superdotación (2 perfiles) ────────
    {
        email: 'miguel.torres@seed.diversia.com',
        firstName: 'Miguel',
        lastName: 'Torres',
        diagnoses: ['encrypted:Altas_Capacidades'],
        accommodationsNeeded: 'encrypted:intellectual_stimulation,autonomy,accelerated_learning_path,skip_repetitive_training',
        experienceYears: 10,
        bio: 'Arquitecto de software con altas capacidades. Aprendo tecnologías nuevas en días, diseño sistemas complejos y necesito retos constantes. La monotonía me desmotiva profundamente.',
        location: 'Barcelona, Spain',
        skills: ['System Architecture', 'Rust', 'Go', 'Kubernetes', 'Cloud Architecture', 'Distributed Systems'],
        experience: [
            { title: 'Principal Engineer', company: 'ScaleTech', startYear: 2021, endYear: null, current: true, description: 'Arquitectura de sistemas distribuidos' },
            { title: 'Senior Developer', company: 'FinTechPro', startYear: 2018, endYear: 2021, current: false, description: 'Backend de alta concurrencia' },
            { title: 'Developer', company: 'StartupLab', startYear: 2015, endYear: 2018, current: false, description: 'Full-stack development' },
        ],
        education: [
            { degree: 'MSc Computer Science', institution: 'ETH Zurich', year: 2015, field: 'Computer Science' },
            { degree: 'Grado en Física', institution: 'Universidad de Barcelona', year: 2013, field: 'Física' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 70000,
            salaryMax: 120000,
            locations: ['Barcelona', 'Remote', 'International'],
            roles: ['Principal Engineer', 'CTO', 'System Architect'],
            industries: ['Technology', 'Finance', 'Research'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-10T09:00:00Z',
            strengths: ['rapid_learning', 'abstract_reasoning', 'system_design', 'multipotential'],
            challenges: ['boredom_with_routine', 'impatience', 'overqualification_perception'],
            score: 96,
            technicalSkills: ['Rust', 'Go', 'Kubernetes'],
            softSkills: ['visionary_thinking', 'mentoring', 'innovation'],
            workStyle: { preferredHours: 'flexible', environment: 'intellectually_stimulating', collaboration: 'senior_peers' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 22, matchesReceived: 8, applicationsSubmitted: 1 },
    },
    {
        email: 'laura.vidal@seed.diversia.com',
        firstName: 'Laura',
        lastName: 'Vidal',
        diagnoses: ['encrypted:Altas_Capacidades'],
        accommodationsNeeded: 'encrypted:challenging_projects,autonomy,no_micromanagement,continuous_learning_budget',
        experienceYears: 5,
        bio: 'Investigadora y profesora con altas capacidades. Mi mente multipotencial me permite conectar disciplinas dispares. Busco entornos que valoren la curiosidad y la innovación.',
        location: 'Madrid, Spain',
        skills: ['Investigación', 'Docencia', 'Estadística', 'R', 'Publicación académica', 'Divulgación'],
        experience: [
            { title: 'Profesora e Investigadora', company: 'Universidad Complutense', startYear: 2023, endYear: null, current: true, description: 'Docencia en psicología cognitiva e investigación' },
            { title: 'Investigadora predoctoral', company: 'CSIC', startYear: 2021, endYear: 2023, current: false, description: 'Neurociencia y cognición' },
        ],
        education: [
            { degree: 'Doctorado en Neurociencia Cognitiva', institution: 'Universidad Complutense', year: 2023, field: 'Neurociencia' },
            { degree: 'Grado en Psicología', institution: 'Universidad Complutense', year: 2019, field: 'Psicología' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 32000,
            salaryMax: 50000,
            locations: ['Madrid', 'Barcelona', 'Remote'],
            roles: ['Investigadora', 'Profesora', 'Consultora de formación'],
            industries: ['Educación', 'Salud', 'Consultoría'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-03T12:00:00Z',
            strengths: ['cross_disciplinary_thinking', 'rapid_comprehension', 'teaching', 'abstract_reasoning'],
            challenges: ['boredom', 'perfectionism', 'difficulty_with_slow_pace'],
            score: 93,
            technicalSkills: ['R', 'Estadística', 'Publicación académica'],
            softSkills: ['teaching', 'critical_thinking', 'innovation'],
            workStyle: { preferredHours: 'flexible', environment: 'academic', collaboration: 'intellectual_exchange' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 14, matchesReceived: 4, applicationsSubmitted: 2 },
    },

    // ─── TANV (Trastorno Aprendizaje No Verbal) (1 perfil) ─────
    {
        email: 'david.ortiz@seed.diversia.com',
        firstName: 'David',
        lastName: 'Ortiz',
        diagnoses: ['encrypted:TANV'],
        accommodationsNeeded: 'encrypted:verbal_instructions,avoid_maps_diagrams,gps_for_routes,explicit_social_cues',
        experienceYears: 4,
        bio: 'Teleoperador y atención al cliente con TANV. Mi capacidad verbal excepcional y memoria auditiva me hacen ideal para atención telefónica. Necesito instrucciones verbales y evitar diagramas.',
        location: 'Sevilla, Spain',
        skills: ['Atención al cliente', 'CRM (Salesforce)', 'Comunicación verbal', 'Resolución de conflictos', 'Ventas telefónicas'],
        experience: [
            { title: 'Agente de atención al cliente', company: 'ServiCall', startYear: 2022, endYear: null, current: true, description: 'Atención telefónica y gestión de incidencias' },
            { title: 'Teleoperador', company: 'ContactCenter Pro', startYear: 2021, endYear: 2022, current: false, description: 'Ventas y soporte telefónico' },
        ],
        education: [
            { degree: 'FP Grado Superior en Administración y Finanzas', institution: 'IES Pablo Picasso', year: 2021, field: 'Administración' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 26000,
            locations: ['Sevilla', 'Remote'],
            roles: ['Atención al cliente', 'Teleoperador', 'Recepcionista'],
            industries: ['Servicios', 'Retail', 'Salud'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-07T10:00:00Z',
            strengths: ['verbal_fluency', 'auditory_memory', 'phone_communication', 'vocabulary'],
            challenges: ['spatial_orientation', 'reading_diagrams', 'nonverbal_social_cues', 'mathematics'],
            score: 71,
            technicalSkills: ['Salesforce', 'CRM', 'Ventas telefónicas'],
            softSkills: ['verbal_communication', 'empathy', 'patience'],
            workStyle: { preferredHours: 'fixed', environment: 'office', collaboration: 'verbal' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 3, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Doble Excepcionalidad: Altas Capacidades + TDAH (1 perfil) ──
    {
        email: 'sofia.chen.w@seed.diversia.com',
        firstName: 'Sofía',
        lastName: 'Chen Wang',
        diagnoses: ['encrypted:Altas_Capacidades', 'encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:intellectual_challenge,flexible_schedule,varied_tasks,minimal_bureaucracy,autonomy',
        experienceYears: 7,
        bio: 'Emprendedora y consultora con doble excepcionalidad (altas capacidades + TDAH). Mi mente va a mil por hora generando ideas, pero necesito estructura externa para ejecutarlas. Combinación explosiva de creatividad y velocidad de aprendizaje.',
        location: 'Barcelona, Spain',
        skills: ['Estrategia empresarial', 'Innovation consulting', 'Design Thinking', 'Lean Startup', 'Public speaking', 'Fundraising'],
        experience: [
            { title: 'Consultora de innovación', company: 'InnovaHub', startYear: 2021, endYear: null, current: true, description: 'Consultoría estratégica para startups y corporaciones' },
            { title: 'Co-fundadora', company: 'NeuroBridge (startup)', startYear: 2019, endYear: 2021, current: false, description: 'Plataforma de neurodiversidad en el trabajo' },
        ],
        education: [
            { degree: 'MBA', institution: 'ESADE', year: 2019, field: 'Business' },
            { degree: 'Grado en Ingeniería Industrial', institution: 'UPC', year: 2017, field: 'Ingeniería' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 50000,
            salaryMax: 80000,
            locations: ['Barcelona', 'Madrid', 'Remote'],
            roles: ['Consultora', 'Directora de innovación', 'Strategy Lead'],
            industries: ['Consultoría', 'Technology', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-18T13:00:00Z',
            strengths: ['rapid_ideation', 'cross_domain_thinking', 'charisma', 'hyperfocus_on_passion_projects'],
            challenges: ['routine_tasks', 'follow_through', 'bureaucracy', 'understimulation'],
            score: 90,
            technicalSkills: ['Design Thinking', 'Strategy', 'Public Speaking'],
            softSkills: ['leadership', 'vision', 'communication', 'creativity'],
            workStyle: { preferredHours: 'flexible', environment: 'dynamic', collaboration: 'leadership' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 18, matchesReceived: 6, applicationsSubmitted: 0 },
    },

    // ─── TOC (Trastorno Obsesivo-Compulsivo) (1 perfil) ────────
    {
        email: 'alberto.jimenez@seed.diversia.com',
        firstName: 'Alberto',
        lastName: 'Jiménez',
        diagnoses: ['encrypted:TOC'],
        accommodationsNeeded: 'encrypted:understanding_rituals,flexibility_for_compulsions,reduced_time_pressure,private_workspace',
        experienceYears: 5,
        bio: 'Contable y auditor con TOC. Mi necesidad de verificación constante es una ventaja en auditoría: detecto errores que otros pasan por alto. Necesito un entorno comprensivo con mis rutinas.',
        location: 'Madrid, Spain',
        skills: ['Contabilidad', 'Auditoría', 'SAP', 'Excel avanzado', 'Normativa fiscal', 'IFRS'],
        experience: [
            { title: 'Auditor junior', company: 'AuditPro', startYear: 2022, endYear: null, current: true, description: 'Auditoría financiera y compliance' },
            { title: 'Contable', company: 'Gestión Fiscal SL', startYear: 2020, endYear: 2022, current: false, description: 'Contabilidad general y fiscal' },
        ],
        education: [
            { degree: 'Grado en ADE', institution: 'Universidad Autónoma de Madrid', year: 2020, field: 'Economía' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 30000,
            salaryMax: 42000,
            locations: ['Madrid'],
            roles: ['Auditor', 'Contable', 'Controller financiero'],
            industries: ['Finance', 'Consultoría', 'Administración'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-11T11:00:00Z',
            strengths: ['error_detection', 'thoroughness', 'verification', 'compliance_adherence'],
            challenges: ['time_pressure', 'interruptions_during_verification', 'accepting_good_enough'],
            score: 84,
            technicalSkills: ['SAP', 'Excel', 'IFRS'],
            softSkills: ['precision', 'integrity', 'methodical_approach'],
            workStyle: { preferredHours: 'fixed', environment: 'private_office', collaboration: 'structured' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ═══════════════════════════════════════════════════════════════
    // NUEVOS CANDIDATOS — Oficios manuales y diagnósticos duales
    // Personas que disfrutan trabajando con las manos
    // ═══════════════════════════════════════════════════════════════

    // ─── TDAH + Dislexia (dual) — Albañil / Construcción ──────
    {
        email: 'fernando.rueda@seed.diversia.com',
        firstName: 'Fernando',
        lastName: 'Rueda',
        diagnoses: ['encrypted:TDAH', 'encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:visual_instructions,no_written_reports,physical_activity,buddy_system,flexible_breaks',
        experienceYears: 8,
        bio: 'Albañil con TDAH y dislexia. Los planos con letras pequeñas me cuestan, pero ponme delante de un muro y levanto la pared más recta que nadie. Mis manos piensan más rápido que mi cabeza con los textos. Necesito instrucciones visuales y un buen compañero de obra.',
        location: 'Sevilla, Spain',
        skills: ['Albañilería', 'Encofrado', 'Solado', 'PRL Construcción', 'Herramientas manuales', 'Lectura de planos simplificados'],
        experience: [
            { title: 'Oficial de albañilería', company: 'Reformas del Sur', startYear: 2020, endYear: null, current: true, description: 'Rehabilitación de viviendas y albañilería general' },
            { title: 'Peón de obra', company: 'Construcciones Betis', startYear: 2017, endYear: 2020, current: false, description: 'Apoyo en obras de nueva construcción' },
        ],
        education: [
            { degree: 'Certificado de Profesionalidad en Albañilería', institution: 'Centro de Formación Profesional Sevilla', year: 2017, field: 'Construcción' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 32000,
            locations: ['Sevilla', 'Málaga', 'Córdoba'],
            roles: ['Albañil', 'Oficial de obra', 'Solador', 'Peón especializado'],
            industries: ['Construcción', 'Reformas', 'Mantenimiento'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-15T08:00:00Z',
            strengths: ['physical_endurance', 'spatial_3d_thinking', 'hands_on_precision', 'problem_solving_practical', 'team_loyalty'],
            challenges: ['reading_written_plans', 'written_documentation', 'long_text_instructions', 'administrative_tasks'],
            score: 75,
            technicalSkills: ['Albañilería', 'Encofrado', 'Solado'],
            softSkills: ['reliability', 'physical_strength', 'team_player'],
            workStyle: { preferredHours: 'early_morning', environment: 'outdoor_physical', collaboration: 'in_person_small_team' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── TEA — Jardinero / Viverista ──────────────────────────
    {
        email: 'adrian.campos@seed.diversia.com',
        firstName: 'Adrián',
        lastName: 'Campos',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:predictable_routine,minimal_social_demands,outdoor_work,written_schedules,sensory_breaks',
        experienceYears: 3,
        bio: 'Viverista con TEA. Las plantas no mienten, no cambian de humor y responden a cuidados sistemáticos. Conozco más de 200 especies por su nombre científico. Mi rutina ideal: llegar al vivero, consultar mi lista de tareas visual y trabajar con la tierra en silencio.',
        location: 'Málaga, Spain',
        skills: ['Jardinería', 'Botánica', 'Identificación de especies', 'Riego sistematizado', 'Control de plagas', 'Trasplante'],
        experience: [
            { title: 'Auxiliar de vivero', company: 'Garden Center Mediterráneo', startYear: 2023, endYear: null, current: true, description: 'Cuidado de plantas, riego y atención a clientes (mínima)' },
            { title: 'Voluntario de jardín botánico', company: 'Jardín Botánico de Málaga', startYear: 2022, endYear: 2023, current: false, description: 'Catalogación y cuidado de colecciones botánicas' },
        ],
        education: [
            { degree: 'FP Grado Medio en Jardinería y Floristería', institution: 'IES El Palo', year: 2022, field: 'Jardinería' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 24000,
            locations: ['Málaga', 'Granada'],
            roles: ['Jardinero', 'Viverista', 'Auxiliar de vivero', 'Cuidador de plantas'],
            industries: ['Agricultura / Viveros', 'Servicios Generales', 'Medio ambiente'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-18T09:00:00Z',
            strengths: ['botanical_knowledge', 'systematic_care', 'pattern_detection_plants', 'routine_adherence', 'attention_to_detail'],
            challenges: ['customer_interaction', 'unexpected_task_changes', 'noisy_environments', 'team_meetings'],
            score: 82,
            technicalSkills: ['Botánica', 'Riego', 'Control de plagas'],
            softSkills: ['patience', 'observation', 'consistency'],
            workStyle: { preferredHours: 'early_morning', environment: 'outdoor_quiet', collaboration: 'independent' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Tourette — Cocinero/a de Línea ───────────────────────
    {
        email: 'rosa.molina@seed.diversia.com',
        firstName: 'Rosa',
        lastName: 'Molina',
        diagnoses: ['encrypted:Sindrome_Tourette'],
        accommodationsNeeded: 'encrypted:understanding_environment,busy_noisy_ok,breaks_when_needed,no_customer_facing,fixed_station',
        experienceYears: 5,
        bio: 'Cocinera de línea con Tourette. La cocina es el lugar perfecto para mí: ruido, movimiento, acción... nadie nota mis tics entre el fragor de los fogones. Mi estación es mi castillo. Cocino con pasión y rapidez.',
        location: 'Valencia, Spain',
        skills: ['Cocina profesional', 'Cocina mediterránea', 'Gestión de tiempos', 'APPCC', 'Emplatado', 'Mise en place'],
        experience: [
            { title: 'Cocinera de línea', company: 'Restaurante La Barraca', startYear: 2022, endYear: null, current: true, description: 'Cocina de línea en restaurante de alta afluencia' },
            { title: 'Ayudante de cocina', company: 'Hotel Mediterráneo', startYear: 2020, endYear: 2022, current: false, description: 'Apoyo en cocina de hotel y preparación de buffets' },
        ],
        education: [
            { degree: 'FP Grado Medio en Cocina y Gastronomía', institution: 'Escuela de Hostelería de Valencia', year: 2020, field: 'Hostelería' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 20000,
            salaryMax: 28000,
            locations: ['Valencia', 'Barcelona', 'Alicante'],
            roles: ['Cocinera de línea', 'Cocinera', 'Chef de partida', 'Ayudante de cocina'],
            industries: ['Restauración', 'Hostelería', 'Alimentación'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-20T10:00:00Z',
            strengths: ['speed', 'multitasking_in_flow', 'heat_tolerance', 'consistency_under_pressure', 'hands_on_creativity'],
            challenges: ['quiet_environments_highlight_tics', 'customer_facing_anxiety', 'new_team_adaptation'],
            score: 78,
            technicalSkills: ['Cocina mediterránea', 'APPCC', 'Emplatado'],
            softSkills: ['resilience', 'determination', 'team_spirit'],
            workStyle: { preferredHours: 'split_shift', environment: 'active_noisy', collaboration: 'kitchen_brigade' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 6, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── TEA (nivel 2 apoyo) — Mecánico de Taller ─────────────
    {
        email: 'oscar.prieto@seed.diversia.com',
        firstName: 'Óscar',
        lastName: 'Prieto',
        diagnoses: ['encrypted:TEA_nivel2'],
        accommodationsNeeded: 'encrypted:structured_environment,visual_manuals,own_workspace,minimal_social_demands,predictable_routine,sensory_protection_noise',
        experienceYears: 6,
        bio: 'Mecánico de taller con TEA nivel 2. Los motores son mi idioma: lógicos, predecibles, reparables. Puedo diagnosticar una avería por el sonido del motor. Necesito mi bahía fija, mis herramientas ordenadas y que no me cambien la rutina sin aviso.',
        location: 'Zaragoza, Spain',
        skills: ['Mecánica general', 'Diagnosis electrónica', 'Inyección diésel', 'Herramientas de taller', 'PRL', 'Electricidad básica del automóvil'],
        experience: [
            { title: 'Mecánico', company: 'Talleres Aranda', startYear: 2021, endYear: null, current: true, description: 'Reparación mecánica general y mantenimiento' },
            { title: 'Aprendiz de mecánico', company: 'Auto Rápido', startYear: 2019, endYear: 2021, current: false, description: 'Aprendizaje de mecánica general con tutor' },
        ],
        education: [
            { degree: 'FP Grado Medio en Electromecánica de Vehículos', institution: 'IES Tiempos Modernos, Zaragoza', year: 2019, field: 'Automoción' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 32000,
            locations: ['Zaragoza', 'Huesca'],
            roles: ['Mecánico', 'Mecánico de taller', 'Técnico de automoción'],
            industries: ['Automoción', 'Transporte', 'Logística'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-22T08:00:00Z',
            strengths: ['auditory_diagnosis', 'systematic_repair', 'tool_organization', 'routine_precision', 'mechanical_intuition'],
            challenges: ['team_meetings', 'unexpected_schedule_changes', 'loud_compressor_noise', 'customer_interaction'],
            score: 83,
            technicalSkills: ['Mecánica general', 'Diagnosis', 'Inyección diésel'],
            softSkills: ['precision', 'reliability', 'deep_focus'],
            workStyle: { preferredHours: 'fixed_morning', environment: 'own_bay_structured', collaboration: 'minimal' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── TDAH — Pintora de Obra / Construcción ────────────────
    {
        email: 'marina.gil@seed.diversia.com',
        firstName: 'Marina',
        lastName: 'Gil',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:music_allowed,movement_allowed,visual_color_guides,flexible_breaks,varied_tasks',
        experienceYears: 4,
        bio: 'Pintora de obra con TDAH. Pintar paredes es mi flow perfecto: movimiento constante, creatividad con colores, resultados visibles al instante. Con mis auriculares y una brocha, el TDAH desaparece. Cada habitación es un lienzo nuevo.',
        location: 'Sevilla, Spain',
        skills: ['Pintura interior', 'Pintura exterior', 'Preparación de superficies', 'Colorimetría', 'Estuco decorativo', 'PRL'],
        experience: [
            { title: 'Pintora de obra', company: 'Pinturas Esperanza', startYear: 2023, endYear: null, current: true, description: 'Pintura en rehabilitaciones y obra nueva' },
            { title: 'Ayudante de pintura', company: 'Reformas Express', startYear: 2021, endYear: 2023, current: false, description: 'Apoyo en trabajos de pintura y acabados' },
        ],
        education: [
            { degree: 'Certificado de Profesionalidad en Pintura Decorativa', institution: 'Centro de Referencia Nacional de Formación, Sevilla', year: 2021, field: 'Construcción' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 20000,
            salaryMax: 28000,
            locations: ['Sevilla', 'Cádiz', 'Huelva'],
            roles: ['Pintora de obra', 'Pintora decorativa', 'Estucadora'],
            industries: ['Construcción', 'Reformas', 'Decoración'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-24T09:00:00Z',
            strengths: ['color_sense', 'physical_stamina', 'creative_finishing', 'fast_execution', 'visible_progress_motivation'],
            challenges: ['waiting_for_paint_to_dry', 'detailed_budgets', 'administrative_tasks', 'monotone_single_color_rooms'],
            score: 76,
            technicalSkills: ['Pintura', 'Colorimetría', 'Estuco'],
            softSkills: ['creativity', 'energy', 'optimism'],
            workStyle: { preferredHours: 'morning', environment: 'active_varied', collaboration: 'small_team' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 2 },
    },

    // ─── Dislexia — Ebanista / Carpintero Artesanal ───────────
    {
        email: 'hector.blanco@seed.diversia.com',
        firstName: 'Héctor',
        lastName: 'Blanco',
        diagnoses: ['encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:visual_blueprints,verbal_instructions,minimal_writing,text_to_speech,hands_on_learning',
        experienceYears: 10,
        bio: 'Ebanista con dislexia. Los manuales escritos me cuestan, pero dime qué mueble quieres y lo construyo sin necesitar ni un plano: lo veo en 3D en mi cabeza. Mi dislexia me dio pensamiento espacial tridimensional y manos que entienden la madera.',
        location: 'Granada, Spain',
        skills: ['Ebanistería', 'Carpintería artesanal', 'Restauración de muebles', 'Tornería', 'Tallado en madera', 'Barnizado', 'Diseño de piezas'],
        experience: [
            { title: 'Ebanista autónomo', company: 'Taller Blanco (Autónomo)', startYear: 2019, endYear: null, current: true, description: 'Creación y restauración de muebles artesanales por encargo' },
            { title: 'Carpintero', company: 'Muebles Sierra Nevada', startYear: 2015, endYear: 2019, current: false, description: 'Carpintería industrial y artesanal' },
        ],
        education: [
            { degree: 'FP Grado Superior en Carpintería y Mueble', institution: 'Escuela de Arte de Granada', year: 2015, field: 'Carpintería' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 24000,
            salaryMax: 34000,
            locations: ['Granada', 'Málaga', 'Jaén'],
            roles: ['Ebanista', 'Carpintero artesanal', 'Restaurador de muebles', 'Tornero'],
            industries: ['Artesanía', 'Construcción', 'Restauración de patrimonio'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-25T10:00:00Z',
            strengths: ['3d_spatial_visualization', 'manual_precision', 'creative_design', 'material_knowledge', 'problem_solving_practical'],
            challenges: ['written_quotes', 'reading_technical_manuals', 'invoicing', 'email_communication'],
            score: 85,
            technicalSkills: ['Ebanistería', 'Tornería', 'Restauración'],
            softSkills: ['craftsmanship', 'patience', 'artistic_vision'],
            workStyle: { preferredHours: 'flexible', environment: 'own_workshop', collaboration: 'independent_or_pair' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 7, matchesReceived: 3, applicationsSubmitted: 1 },
    },

    // ─── TAG + TDAH (dual) — Ceramista / Artesana ─────────────
    {
        email: 'carmen.saez@seed.diversia.com',
        firstName: 'Carmen',
        lastName: 'Sáez',
        diagnoses: ['encrypted:TAG_Ansiedad_Generalizada', 'encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:rhythmic_repetitive_work,quiet_workspace,own_pace,no_time_pressure,sensory_grounding,flexible_schedule',
        experienceYears: 4,
        bio: 'Ceramista con TAG y TDAH. La ansiedad me paralizaba en trabajos de oficina, pero el torno de alfarero me salva la vida cada día. El barro entre mis manos me ancla al presente. El TDAH me da la creatividad para diseñar piezas únicas, y la repetición del torno calma mi ansiedad.',
        location: 'Granada, Spain',
        skills: ['Cerámica', 'Torno de alfarero', 'Esmaltado', 'Modelado manual', 'Hornos cerámicos', 'Diseño de piezas'],
        experience: [
            { title: 'Ceramista', company: 'Taller Albayzín Cerámica', startYear: 2023, endYear: null, current: true, description: 'Creación de piezas cerámicas artesanales y cursos' },
            { title: 'Aprendiz de cerámica', company: 'Cooperativa de Artesanos de Granada', startYear: 2021, endYear: 2023, current: false, description: 'Aprendizaje de técnicas cerámicas tradicionales' },
        ],
        education: [
            { degree: 'Grado en Bellas Artes (especialidad Cerámica)', institution: 'Universidad de Granada', year: 2021, field: 'Arte' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 26000,
            locations: ['Granada', 'Málaga', 'Sevilla'],
            roles: ['Ceramista', 'Alfarera', 'Artesana', 'Monitora de taller'],
            industries: ['Artesanía', 'Educación', 'Cultura'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-26T11:00:00Z',
            strengths: ['artistic_creativity', 'rhythmic_work', 'sensory_grounding', 'tactile_sensitivity', 'design_vision'],
            challenges: ['deadlines_create_panic', 'administrative_tasks', 'crowded_environments', 'phone_calls'],
            score: 74,
            technicalSkills: ['Cerámica', 'Torno', 'Esmaltado'],
            softSkills: ['artistic_sensitivity', 'patience_in_craft', 'teaching_ability'],
            workStyle: { preferredHours: 'flexible_morning', environment: 'quiet_workshop', collaboration: 'independent_or_small_group' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Bipolar tipo II — Peón Agrícola / Jardinero ──────────
    {
        email: 'tomas.guerrero@seed.diversia.com',
        firstName: 'Tomás',
        lastName: 'Guerrero',
        diagnoses: ['encrypted:Trastorno_Bipolar_tipo_II'],
        accommodationsNeeded: 'encrypted:flexible_schedule_for_episodes,outdoor_work,physical_activity,understanding_absences,reduced_social_pressure,predictable_seasonal_work',
        experienceYears: 6,
        bio: 'Peón agrícola y jardinero con trastorno bipolar tipo II. La tierra no pregunta cómo estás hoy. En mis fases de hipomanía soy el trabajador más productivo del campo. En mis fases bajas, las tareas repetitivas al aire libre me mantienen en pie. El sol y la actividad física son mi mejor medicina complementaria.',
        location: 'Málaga, Spain',
        skills: ['Agricultura', 'Jardinería', 'Poda de frutales', 'Riego', 'Maquinaria agrícola', 'Trabajo físico', 'Conocimiento estacional'],
        experience: [
            { title: 'Peón agrícola', company: 'Finca Los Almendros', startYear: 2021, endYear: null, current: true, description: 'Cultivo, poda y recolección de frutales' },
            { title: 'Jardinero', company: 'Ayuntamiento de Málaga (subcontrata)', startYear: 2019, endYear: 2021, current: false, description: 'Mantenimiento de jardines públicos' },
        ],
        education: [
            { degree: 'FP Grado Medio en Producción Agroecológica', institution: 'IES La Rosaleda, Málaga', year: 2019, field: 'Agricultura' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 24000,
            locations: ['Málaga', 'Granada', 'Almería'],
            roles: ['Peón agrícola', 'Jardinero', 'Auxiliar de vivero', 'Operario de finca'],
            industries: ['Agricultura / Viveros', 'Servicios Generales', 'Medio ambiente'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-28T08:00:00Z',
            strengths: ['physical_endurance', 'seasonal_knowledge', 'nature_connection', 'hypomania_productivity', 'outdoor_resilience'],
            challenges: ['depressive_episodes', 'winter_months', 'social_energy_fluctuations', 'long_indoor_periods'],
            score: 70,
            technicalSkills: ['Agricultura', 'Poda', 'Maquinaria agrícola'],
            softSkills: ['resilience', 'self_awareness', 'honesty'],
            workStyle: { preferredHours: 'early_morning', environment: 'outdoor_physical', collaboration: 'small_team_or_alone' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 3, matchesReceived: 2, applicationsSubmitted: 1 },
    },
]
