// ═══════════════════════════════════════════════════════════════════
// CANDIDATOS NEURODIVERGENTES — 16 perfiles diversos
// Dominio: @seed.diversia.com (NUNCA mezclar con datos reales)
// Cada perfil refleja una idiosincrasia única y real
// ═══════════════════════════════════════════════════════════════════

export const candidateProfiles = [
    // ─── TDAH (3 perfiles) ───────────────────────────────────────
    {
        email: 'carlos.martinez@seed.diversia.com',
        firstName: 'Carlos',
        lastName: 'Martínez',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:flexible_schedule,noise_cancelling,task_chunking',
        experienceYears: 5,
        bio: 'Desarrollador frontend con TDAH. Mi hiperfoco me permite resolver bugs complejos en horas que a otros les llevan días. Trabajo mejor con plazos cortos y tareas bien definidas.',
        location: 'Madrid, Spain',
        skills: ['React', 'Next.js', 'TypeScript', 'CSS', 'Figma'],
        experience: [
            { title: 'Frontend Developer', company: 'StartupX', startYear: 2022, endYear: null, current: true, description: 'Desarrollo de SPA con React/Next.js' },
            { title: 'Junior Developer', company: 'WebAgency', startYear: 2020, endYear: 2022, current: false, description: 'Maquetación y desarrollo web' },
        ],
        education: [
            { degree: 'Grado en Ingeniería Informática', institution: 'Universidad Politécnica de Madrid', year: 2020, field: 'Informática' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 35000,
            salaryMax: 55000,
            locations: ['Madrid', 'Remote'],
            roles: ['Frontend Developer', 'Full-stack Developer'],
            industries: ['Technology', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-15T10:00:00Z',
            strengths: ['hyperfocus', 'creative_thinking', 'pattern_recognition', 'rapid_prototyping'],
            challenges: ['time_management', 'task_switching', 'sustained_attention_on_boring_tasks'],
            score: 78,
            technicalSkills: ['React', 'TypeScript', 'CSS'],
            softSkills: ['creativity', 'problem_solving', 'enthusiasm'],
            workStyle: { preferredHours: 'flexible', environment: 'quiet', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 15, matchesReceived: 4, applicationsSubmitted: 2 },
    },
    {
        email: 'lucia.fernandez@seed.diversia.com',
        firstName: 'Lucía',
        lastName: 'Fernández',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:pomodoro_timer,standing_desk,visual_reminders',
        experienceYears: 3,
        bio: 'Chef de repostería con TDAH. La cocina es mi espacio de hiperfoco perfecto: tareas manuales, creatividad y resultados inmediatos. Necesito listas claras y un ambiente donde pueda moverme.',
        location: 'Valencia, Spain',
        skills: ['Repostería creativa', 'Pastelería', 'Decoración', 'Gestión de cocina', 'APPCC'],
        experience: [
            { title: 'Chef de repostería', company: 'Dulce Hogar', startYear: 2023, endYear: null, current: true, description: 'Creación de postres y gestión de obrador' },
            { title: 'Ayudante de cocina', company: 'Restaurante El Faro', startYear: 2021, endYear: 2023, current: false, description: 'Apoyo en cocina y elaboración de postres' },
        ],
        education: [
            { degree: 'Técnico en Cocina y Gastronomía', institution: 'Escuela de Hostelería de Valencia', year: 2021, field: 'Hostelería' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 30000,
            locations: ['Valencia', 'Barcelona'],
            roles: ['Chef de repostería', 'Pastelera', 'Ayudante de cocina'],
            industries: ['Restauración', 'Alimentación'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-01T09:00:00Z',
            strengths: ['creativity', 'hands_on_work', 'sensory_precision', 'energy'],
            challenges: ['time_estimation', 'paperwork', 'following_long_recipes_without_visual_aid'],
            score: 72,
            technicalSkills: ['Repostería', 'APPCC', 'Decoración'],
            softSkills: ['creativity', 'teamwork', 'adaptability'],
            workStyle: { preferredHours: 'morning', environment: 'active', collaboration: 'in_person' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 8, matchesReceived: 2, applicationsSubmitted: 1 },
    },
    {
        email: 'diego.romero@seed.diversia.com',
        firstName: 'Diego',
        lastName: 'Romero',
        diagnoses: ['encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:flexible_breaks,movement_allowed,clear_task_lists',
        experienceYears: 7,
        bio: 'Técnico de mantenimiento con TDAH. Resuelvo problemas mecánicos y eléctricos con rapidez porque mi mente conecta causas y efectos de forma no lineal. Necesito variedad de tareas.',
        location: 'Sevilla, Spain',
        skills: ['Electricidad', 'Fontanería', 'Climatización', 'Mantenimiento preventivo', 'PRL'],
        experience: [
            { title: 'Técnico de mantenimiento', company: 'Hotel Gran Vía', startYear: 2020, endYear: null, current: true, description: 'Mantenimiento integral de instalaciones' },
            { title: 'Electricista', company: 'InstalaSur', startYear: 2018, endYear: 2020, current: false, description: 'Instalaciones eléctricas y reparaciones' },
        ],
        education: [
            { degree: 'FP Grado Superior en Mantenimiento Electromecánico', institution: 'IES Politécnico de Sevilla', year: 2018, field: 'Mantenimiento' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 24000,
            salaryMax: 35000,
            locations: ['Sevilla', 'Málaga'],
            roles: ['Técnico de mantenimiento', 'Electricista', 'Operario'],
            industries: ['Servicios Generales', 'Hostelería', 'Logística'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-20T11:00:00Z',
            strengths: ['troubleshooting', 'hands_on_problem_solving', 'energy', 'multitasking_physical'],
            challenges: ['documentation', 'waiting', 'repetitive_tasks'],
            score: 74,
            technicalSkills: ['Electricidad', 'Climatización', 'PRL'],
            softSkills: ['initiative', 'adaptability', 'resourcefulness'],
            workStyle: { preferredHours: 'morning', environment: 'varied', collaboration: 'small_team' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 6, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── TEA / Autismo (3 perfiles) ─────────────────────────────
    {
        email: 'ana.garcia@seed.diversia.com',
        firstName: 'Ana',
        lastName: 'García',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:written_instructions,predictable_schedule,quiet_workspace,advance_notice_of_changes',
        experienceYears: 4,
        bio: 'Data scientist en el espectro autista. Mi capacidad para detectar patrones en grandes datasets es mi mayor fortaleza. Trabajo mejor con rutinas claras y comunicación escrita.',
        location: 'Barcelona, Spain',
        skills: ['Python', 'Data Science', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas'],
        experience: [
            { title: 'Data Analyst', company: 'DataFlow', startYear: 2023, endYear: null, current: true, description: 'ML pipelines y análisis de datos' },
            { title: 'Junior Data Scientist', company: 'AnalyticsCo', startYear: 2022, endYear: 2023, current: false, description: 'Modelos predictivos' },
        ],
        education: [
            { degree: 'MSc Data Science', institution: 'Universitat de Barcelona', year: 2022, field: 'Data Science' },
            { degree: 'Grado en Matemáticas', institution: 'Universitat de Barcelona', year: 2020, field: 'Matemáticas' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 40000,
            salaryMax: 60000,
            locations: ['Barcelona', 'Remote'],
            roles: ['Data Scientist', 'ML Engineer', 'Data Analyst'],
            industries: ['Technology', 'Healthcare', 'Finance'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-01T14:30:00Z',
            strengths: ['pattern_recognition', 'systematic_thinking', 'detail_orientation', 'data_analysis'],
            challenges: ['social_interactions', 'sensory_overload', 'unexpected_changes'],
            score: 88,
            technicalSkills: ['Python', 'SQL', 'TensorFlow'],
            softSkills: ['analytical_thinking', 'thoroughness', 'reliability'],
            workStyle: { preferredHours: 'fixed', environment: 'predictable', collaboration: 'structured' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 10, matchesReceived: 5, applicationsSubmitted: 1 },
    },
    {
        email: 'marcos.delgado@seed.diversia.com',
        firstName: 'Marcos',
        lastName: 'Delgado',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:structured_environment,visual_schedules,minimal_sensory_stimulation,clear_hierarchy',
        experienceYears: 6,
        bio: 'Técnico de control de calidad alimentaria. Mi atención al detalle extrema y mi capacidad para seguir protocolos al pie de la letra son ideales para garantizar la seguridad alimentaria.',
        location: 'Zaragoza, Spain',
        skills: ['Control de calidad', 'APPCC', 'ISO 22000', 'Análisis microbiológico', 'Trazabilidad', 'Documentación técnica'],
        experience: [
            { title: 'Técnico de calidad', company: 'AlimentosPuros S.A.', startYear: 2021, endYear: null, current: true, description: 'Control de calidad y auditorías internas' },
            { title: 'Auxiliar de laboratorio', company: 'LabAliment', startYear: 2019, endYear: 2021, current: false, description: 'Análisis microbiológicos de alimentos' },
        ],
        education: [
            { degree: 'Grado en Ciencia y Tecnología de los Alimentos', institution: 'Universidad de Zaragoza', year: 2019, field: 'Alimentación' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 28000,
            salaryMax: 38000,
            locations: ['Zaragoza', 'Barcelona'],
            roles: ['Técnico de calidad', 'Auditor alimentario', 'Analista de laboratorio'],
            industries: ['Alimentación', 'Salud', 'Farmacéutica'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-28T09:00:00Z',
            strengths: ['protocol_adherence', 'detail_orientation', 'systematic_documentation', 'pattern_detection'],
            challenges: ['team_meetings', 'sensory_sensitivity_to_smells', 'adapting_to_new_procedures'],
            score: 91,
            technicalSkills: ['APPCC', 'ISO 22000', 'Microbiología'],
            softSkills: ['precision', 'reliability', 'consistency'],
            workStyle: { preferredHours: 'fixed', environment: 'structured_lab', collaboration: 'minimal' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 7, matchesReceived: 3, applicationsSubmitted: 1 },
    },
    {
        email: 'irene.lopez@seed.diversia.com',
        firstName: 'Irene',
        lastName: 'López',
        diagnoses: ['encrypted:TEA'],
        accommodationsNeeded: 'encrypted:written_communication,reduced_social_demands,consistent_routine,sensory_breaks',
        experienceYears: 2,
        bio: 'Operaria de almacén con TEA. Me apasiona el orden y la organización. Gestiono inventarios con precisión milimétrica y disfruto el trabajo metódico y repetitivo.',
        location: 'Bilbao, Spain',
        skills: ['Gestión de inventarios', 'Picking', 'WMS (SAP)', 'Organización de almacén', 'Carretilla elevadora'],
        experience: [
            { title: 'Operaria de almacén', company: 'LogiNorte', startYear: 2024, endYear: null, current: true, description: 'Picking, packing y gestión de inventario con WMS' },
        ],
        education: [
            { degree: 'FP Grado Medio en Actividades Comerciales', institution: 'IES Txurdinaga', year: 2023, field: 'Comercio' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 24000,
            locations: ['Bilbao', 'Vitoria'],
            roles: ['Operaria de almacén', 'Gestión de inventarios', 'Reponedora'],
            industries: ['Logística', 'Retail', 'Alimentación'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-10T08:00:00Z',
            strengths: ['organization', 'precision', 'routine_adherence', 'inventory_accuracy'],
            challenges: ['social_interaction', 'noisy_environments', 'task_interruptions'],
            score: 80,
            technicalSkills: ['WMS SAP', 'Carretilla', 'Inventarios'],
            softSkills: ['reliability', 'attention_to_detail', 'consistency'],
            workStyle: { preferredHours: 'fixed_morning', environment: 'organized', collaboration: 'independent' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Dislexia (2 perfiles) ──────────────────────────────────
    {
        email: 'pablo.herrera@seed.diversia.com',
        firstName: 'Pablo',
        lastName: 'Herrera',
        diagnoses: ['encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:text_to_speech,extra_time_reading,visual_aids,spell_checker',
        experienceYears: 8,
        bio: 'Diseñador gráfico con dislexia. Mi pensamiento visual tridimensional me permite crear diseños que otros no pueden imaginar. Necesito herramientas de corrección y tiempo extra para textos largos.',
        location: 'Madrid, Spain',
        skills: ['Adobe Photoshop', 'Illustrator', 'Figma', 'Diseño UX/UI', 'Branding', 'Fotografía'],
        experience: [
            { title: 'Senior Designer', company: 'BrandStudio', startYear: 2020, endYear: null, current: true, description: 'Dirección de arte y branding para startups' },
            { title: 'Graphic Designer', company: 'CreativeAgency', startYear: 2017, endYear: 2020, current: false, description: 'Diseño gráfico y web' },
        ],
        education: [
            { degree: 'Grado en Diseño Gráfico', institution: 'Escuela de Arte y Diseño de Madrid', year: 2017, field: 'Diseño' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 38000,
            salaryMax: 52000,
            locations: ['Madrid', 'Remote'],
            roles: ['Diseñador Gráfico', 'UX Designer', 'Director de Arte'],
            industries: ['Technology', 'Marketing', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-22T15:00:00Z',
            strengths: ['visual_thinking_3d', 'spatial_reasoning', 'creativity', 'big_picture_thinking'],
            challenges: ['reading_speed', 'spelling', 'written_documentation'],
            score: 82,
            technicalSkills: ['Photoshop', 'Figma', 'Illustrator'],
            softSkills: ['visual_communication', 'creativity', 'empathy'],
            workStyle: { preferredHours: 'flexible', environment: 'visual_rich', collaboration: 'visual_tools' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 11, matchesReceived: 4, applicationsSubmitted: 2 },
    },
    {
        email: 'nuria.santos@seed.diversia.com',
        firstName: 'Nuria',
        lastName: 'Santos',
        diagnoses: ['encrypted:Dislexia'],
        accommodationsNeeded: 'encrypted:audio_instructions,visual_schedules,dictation_software,reduced_written_reports',
        experienceYears: 4,
        bio: 'Educadora social con dislexia. Mi empatía y capacidad de conectar emocionalmente con las personas compensa con creces mi dificultad con los textos. Uso herramientas de dictado para informes.',
        location: 'Granada, Spain',
        skills: ['Trabajo social', 'Mediación', 'Educación no formal', 'Dinamización grupal', 'Intervención social'],
        experience: [
            { title: 'Educadora social', company: 'Fundación Abrigo', startYear: 2022, endYear: null, current: true, description: 'Acompañamiento a personas en riesgo de exclusión' },
            { title: 'Monitora de ocio', company: 'Asociación Viento', startYear: 2020, endYear: 2022, current: false, description: 'Actividades de ocio inclusivo para jóvenes' },
        ],
        education: [
            { degree: 'Grado en Educación Social', institution: 'Universidad de Granada', year: 2020, field: 'Educación Social' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 22000,
            salaryMax: 30000,
            locations: ['Granada', 'Málaga', 'Sevilla'],
            roles: ['Educadora social', 'Trabajadora social', 'Coordinadora de proyectos'],
            industries: ['ONG', 'Educación', 'Servicios Sociales'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-05T10:00:00Z',
            strengths: ['emotional_intelligence', 'verbal_communication', 'empathy', 'narrative_thinking'],
            challenges: ['written_reports', 'reading_long_documents', 'form_filling'],
            score: 76,
            technicalSkills: ['Mediación', 'Dinamización', 'Intervención social'],
            softSkills: ['empathy', 'communication', 'leadership'],
            workStyle: { preferredHours: 'morning', environment: 'social', collaboration: 'in_person' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Discalculia (1 perfil) ─────────────────────────────────
    {
        email: 'elena.ruiz@seed.diversia.com',
        firstName: 'Elena',
        lastName: 'Ruiz',
        diagnoses: ['encrypted:Discalculia'],
        accommodationsNeeded: 'encrypted:calculator_always,visual_math_aids,extra_time_for_numbers,no_mental_arithmetic',
        experienceYears: 5,
        bio: 'Periodista y copywriter con discalculia. Mi habilidad verbal es excepcional y compenso mi dificultad con números usando siempre calculadora. Redacto contenido persuasivo y creativo.',
        location: 'Barcelona, Spain',
        skills: ['Redacción', 'SEO', 'Copywriting', 'Redes sociales', 'WordPress', 'Storytelling'],
        experience: [
            { title: 'Content Manager', company: 'DigitalBrand', startYear: 2022, endYear: null, current: true, description: 'Estrategia de contenidos y copywriting' },
            { title: 'Redactora', company: 'Periódico Local', startYear: 2020, endYear: 2022, current: false, description: 'Redacción de noticias y reportajes' },
        ],
        education: [
            { degree: 'Grado en Periodismo', institution: 'Universitat Autònoma de Barcelona', year: 2020, field: 'Comunicación' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 28000,
            salaryMax: 40000,
            locations: ['Barcelona', 'Remote'],
            roles: ['Content Manager', 'Copywriter', 'Redactora'],
            industries: ['Marketing', 'Education', 'ONG'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-01-30T11:00:00Z',
            strengths: ['verbal_fluency', 'storytelling', 'conceptual_thinking', 'writing'],
            challenges: ['numerical_tasks', 'budgets', 'statistics', 'invoicing'],
            score: 73,
            technicalSkills: ['SEO', 'WordPress', 'Copywriting'],
            softSkills: ['communication', 'creativity', 'persuasion'],
            workStyle: { preferredHours: 'flexible', environment: 'creative', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 9, matchesReceived: 3, applicationsSubmitted: 2 },
    },

    // ─── Dispraxia / TDC (1 perfil) ────────────────────────────
    {
        email: 'jorge.navarro@seed.diversia.com',
        firstName: 'Jorge',
        lastName: 'Navarro',
        diagnoses: ['encrypted:Dispraxia_TDC'],
        accommodationsNeeded: 'encrypted:ergonomic_equipment,voice_input,extra_time_writing,minimal_handwriting',
        experienceYears: 6,
        bio: 'Consultor de accesibilidad con dispraxia. Mi experiencia personal me da una perspectiva única para diseñar entornos accesibles. Uso dictado por voz y herramientas adaptadas.',
        location: 'Madrid, Spain',
        skills: ['Consultoría accesibilidad', 'WCAG 2.1', 'UX Research', 'Evaluación ergonómica', 'Normativa accesibilidad'],
        experience: [
            { title: 'Consultor de accesibilidad', company: 'AccesibleYA', startYear: 2021, endYear: null, current: true, description: 'Auditorías de accesibilidad web y física' },
            { title: 'UX Researcher', company: 'UserFirst', startYear: 2019, endYear: 2021, current: false, description: 'Investigación de experiencia de usuario' },
        ],
        education: [
            { degree: 'Máster en Interacción Persona-Ordenador', institution: 'Universidad Carlos III', year: 2019, field: 'HCI' },
            { degree: 'Grado en Psicología', institution: 'UNED', year: 2017, field: 'Psicología' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 35000,
            salaryMax: 48000,
            locations: ['Madrid', 'Remote'],
            roles: ['Consultor accesibilidad', 'UX Researcher', 'Especialista D&I'],
            industries: ['Technology', 'Consultoría', 'Educación'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-08T14:00:00Z',
            strengths: ['strategic_thinking', 'empathy', 'resilience', 'verbal_reasoning'],
            challenges: ['fine_motor_skills', 'handwriting', 'spatial_organization', 'physical_coordination'],
            score: 79,
            technicalSkills: ['WCAG', 'UX Research', 'Accesibilidad'],
            softSkills: ['empathy', 'strategic_thinking', 'advocacy'],
            workStyle: { preferredHours: 'flexible', environment: 'ergonomic', collaboration: 'video_calls' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 7, matchesReceived: 3, applicationsSubmitted: 1 },
    },

    // ─── Síndrome de Tourette (1 perfil) ────────────────────────
    {
        email: 'raul.castro@seed.diversia.com',
        firstName: 'Raúl',
        lastName: 'Castro',
        diagnoses: ['encrypted:Sindrome_Tourette'],
        accommodationsNeeded: 'encrypted:understanding_environment,breaks_when_needed,private_workspace_option,no_customer_facing_pressure',
        experienceYears: 4,
        bio: 'Programador backend con síndrome de Tourette. Mi determinación y enfoque intenso me permiten escribir código limpio y eficiente. Trabajo mejor en entornos comprensivos donde puedo tomar descansos.',
        location: 'Málaga, Spain',
        skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'AWS', 'Testing'],
        experience: [
            { title: 'Backend Developer', company: 'CloudOps', startYear: 2023, endYear: null, current: true, description: 'Microservicios con Spring Boot' },
            { title: 'Junior Developer', company: 'TechMálaga', startYear: 2021, endYear: 2023, current: false, description: 'Desarrollo Java y APIs REST' },
        ],
        education: [
            { degree: 'Grado en Ingeniería del Software', institution: 'Universidad de Málaga', year: 2021, field: 'Software' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 32000,
            salaryMax: 48000,
            locations: ['Málaga', 'Remote'],
            roles: ['Backend Developer', 'Full-stack Developer', 'DevOps'],
            industries: ['Technology', 'Finance'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-12T10:00:00Z',
            strengths: ['determination', 'intense_focus', 'clean_code', 'perseverance'],
            challenges: ['tic_management', 'public_speaking', 'high_pressure_situations'],
            score: 81,
            technicalSkills: ['Java', 'Spring Boot', 'Docker'],
            softSkills: ['determination', 'focus', 'resilience'],
            workStyle: { preferredHours: 'flexible', environment: 'private', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 5, matchesReceived: 3, applicationsSubmitted: 1 },
    },

    // ─── TPS (Procesamiento Sensorial) (1 perfil) ──────────────
    {
        email: 'clara.medina@seed.diversia.com',
        firstName: 'Clara',
        lastName: 'Medina',
        diagnoses: ['encrypted:TPS_Procesamiento_Sensorial'],
        accommodationsNeeded: 'encrypted:noise_cancelling,dim_lighting,scent_free_environment,sensory_breaks,no_open_office',
        experienceYears: 3,
        bio: 'Ilustradora y artista digital con TPS. Mi hipersensibilidad sensorial alimenta mi arte: percibo matices de color y textura que otros no ven. Necesito control sobre mi entorno sensorial.',
        location: 'Valencia, Spain',
        skills: ['Ilustración digital', 'Procreate', 'Adobe Creative Suite', 'Animación 2D', 'Storyboarding'],
        experience: [
            { title: 'Ilustradora freelance', company: 'Autónoma', startYear: 2023, endYear: null, current: true, description: 'Ilustración para editoriales y marcas' },
            { title: 'Artista junior', company: 'AnimaStudio', startYear: 2022, endYear: 2023, current: false, description: 'Animación 2D para publicidad' },
        ],
        education: [
            { degree: 'Grado en Bellas Artes', institution: 'Universidad Politécnica de Valencia', year: 2022, field: 'Arte' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 24000,
            salaryMax: 36000,
            locations: ['Valencia', 'Remote'],
            roles: ['Ilustradora', 'Artista digital', 'Animadora 2D'],
            industries: ['Marketing', 'Education', 'Entertainment'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-14T16:00:00Z',
            strengths: ['color_perception', 'texture_sensitivity', 'artistic_vision', 'detail_in_visual_work'],
            challenges: ['noisy_environments', 'strong_smells', 'fluorescent_lighting', 'crowds'],
            score: 77,
            technicalSkills: ['Procreate', 'Photoshop', 'Animación 2D'],
            softSkills: ['artistic_sensitivity', 'observation', 'patience'],
            workStyle: { preferredHours: 'flexible', environment: 'controlled_sensory', collaboration: 'async' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 6, matchesReceived: 2, applicationsSubmitted: 0 },
    },

    // ─── Altas Capacidades / Superdotación (2 perfiles) ────────
    {
        email: 'miguel.torres@seed.diversia.com',
        firstName: 'Miguel',
        lastName: 'Torres',
        diagnoses: ['encrypted:Altas_Capacidades'],
        accommodationsNeeded: 'encrypted:intellectual_stimulation,autonomy,accelerated_learning_path,skip_repetitive_training',
        experienceYears: 10,
        bio: 'Arquitecto de software con altas capacidades. Aprendo tecnologías nuevas en días, diseño sistemas complejos y necesito retos constantes. La monotonía me desmotiva profundamente.',
        location: 'Barcelona, Spain',
        skills: ['System Architecture', 'Rust', 'Go', 'Kubernetes', 'Cloud Architecture', 'Distributed Systems'],
        experience: [
            { title: 'Principal Engineer', company: 'ScaleTech', startYear: 2021, endYear: null, current: true, description: 'Arquitectura de sistemas distribuidos' },
            { title: 'Senior Developer', company: 'FinTechPro', startYear: 2018, endYear: 2021, current: false, description: 'Backend de alta concurrencia' },
            { title: 'Developer', company: 'StartupLab', startYear: 2015, endYear: 2018, current: false, description: 'Full-stack development' },
        ],
        education: [
            { degree: 'MSc Computer Science', institution: 'ETH Zurich', year: 2015, field: 'Computer Science' },
            { degree: 'Grado en Física', institution: 'Universidad de Barcelona', year: 2013, field: 'Física' },
        ],
        preferences: {
            workMode: 'remote',
            salaryMin: 70000,
            salaryMax: 120000,
            locations: ['Barcelona', 'Remote', 'International'],
            roles: ['Principal Engineer', 'CTO', 'System Architect'],
            industries: ['Technology', 'Finance', 'Research'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-10T09:00:00Z',
            strengths: ['rapid_learning', 'abstract_reasoning', 'system_design', 'multipotential'],
            challenges: ['boredom_with_routine', 'impatience', 'overqualification_perception'],
            score: 96,
            technicalSkills: ['Rust', 'Go', 'Kubernetes'],
            softSkills: ['visionary_thinking', 'mentoring', 'innovation'],
            workStyle: { preferredHours: 'flexible', environment: 'intellectually_stimulating', collaboration: 'senior_peers' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 22, matchesReceived: 8, applicationsSubmitted: 1 },
    },
    {
        email: 'laura.vidal@seed.diversia.com',
        firstName: 'Laura',
        lastName: 'Vidal',
        diagnoses: ['encrypted:Altas_Capacidades'],
        accommodationsNeeded: 'encrypted:challenging_projects,autonomy,no_micromanagement,continuous_learning_budget',
        experienceYears: 5,
        bio: 'Investigadora y profesora con altas capacidades. Mi mente multipotencial me permite conectar disciplinas dispares. Busco entornos que valoren la curiosidad y la innovación.',
        location: 'Madrid, Spain',
        skills: ['Investigación', 'Docencia', 'Estadística', 'R', 'Publicación académica', 'Divulgación'],
        experience: [
            { title: 'Profesora e Investigadora', company: 'Universidad Complutense', startYear: 2023, endYear: null, current: true, description: 'Docencia en psicología cognitiva e investigación' },
            { title: 'Investigadora predoctoral', company: 'CSIC', startYear: 2021, endYear: 2023, current: false, description: 'Neurociencia y cognición' },
        ],
        education: [
            { degree: 'Doctorado en Neurociencia Cognitiva', institution: 'Universidad Complutense', year: 2023, field: 'Neurociencia' },
            { degree: 'Grado en Psicología', institution: 'Universidad Complutense', year: 2019, field: 'Psicología' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 32000,
            salaryMax: 50000,
            locations: ['Madrid', 'Barcelona', 'Remote'],
            roles: ['Investigadora', 'Profesora', 'Consultora de formación'],
            industries: ['Educación', 'Salud', 'Consultoría'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: false, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-02-03T12:00:00Z',
            strengths: ['cross_disciplinary_thinking', 'rapid_comprehension', 'teaching', 'abstract_reasoning'],
            challenges: ['boredom', 'perfectionism', 'difficulty_with_slow_pace'],
            score: 93,
            technicalSkills: ['R', 'Estadística', 'Publicación académica'],
            softSkills: ['teaching', 'critical_thinking', 'innovation'],
            workStyle: { preferredHours: 'flexible', environment: 'academic', collaboration: 'intellectual_exchange' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 14, matchesReceived: 4, applicationsSubmitted: 2 },
    },

    // ─── TANV (Trastorno Aprendizaje No Verbal) (1 perfil) ─────
    {
        email: 'david.ortiz@seed.diversia.com',
        firstName: 'David',
        lastName: 'Ortiz',
        diagnoses: ['encrypted:TANV'],
        accommodationsNeeded: 'encrypted:verbal_instructions,avoid_maps_diagrams,gps_for_routes,explicit_social_cues',
        experienceYears: 4,
        bio: 'Teleoperador y atención al cliente con TANV. Mi capacidad verbal excepcional y memoria auditiva me hacen ideal para atención telefónica. Necesito instrucciones verbales y evitar diagramas.',
        location: 'Sevilla, Spain',
        skills: ['Atención al cliente', 'CRM (Salesforce)', 'Comunicación verbal', 'Resolución de conflictos', 'Ventas telefónicas'],
        experience: [
            { title: 'Agente de atención al cliente', company: 'ServiCall', startYear: 2022, endYear: null, current: true, description: 'Atención telefónica y gestión de incidencias' },
            { title: 'Teleoperador', company: 'ContactCenter Pro', startYear: 2021, endYear: 2022, current: false, description: 'Ventas y soporte telefónico' },
        ],
        education: [
            { degree: 'FP Grado Superior en Administración y Finanzas', institution: 'IES Pablo Picasso', year: 2021, field: 'Administración' },
        ],
        preferences: {
            workMode: 'on-site',
            salaryMin: 18000,
            salaryMax: 26000,
            locations: ['Sevilla', 'Remote'],
            roles: ['Atención al cliente', 'Teleoperador', 'Recepcionista'],
            industries: ['Servicios', 'Retail', 'Salud'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-07T10:00:00Z',
            strengths: ['verbal_fluency', 'auditory_memory', 'phone_communication', 'vocabulary'],
            challenges: ['spatial_orientation', 'reading_diagrams', 'nonverbal_social_cues', 'mathematics'],
            score: 71,
            technicalSkills: ['Salesforce', 'CRM', 'Ventas telefónicas'],
            softSkills: ['verbal_communication', 'empathy', 'patience'],
            workStyle: { preferredHours: 'fixed', environment: 'office', collaboration: 'verbal' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 3, matchesReceived: 2, applicationsSubmitted: 1 },
    },

    // ─── Doble Excepcionalidad: Altas Capacidades + TDAH (1 perfil) ──
    {
        email: 'sofia.chen.w@seed.diversia.com',
        firstName: 'Sofía',
        lastName: 'Chen Wang',
        diagnoses: ['encrypted:Altas_Capacidades', 'encrypted:TDAH'],
        accommodationsNeeded: 'encrypted:intellectual_challenge,flexible_schedule,varied_tasks,minimal_bureaucracy,autonomy',
        experienceYears: 7,
        bio: 'Emprendedora y consultora con doble excepcionalidad (altas capacidades + TDAH). Mi mente va a mil por hora generando ideas, pero necesito estructura externa para ejecutarlas. Combinación explosiva de creatividad y velocidad de aprendizaje.',
        location: 'Barcelona, Spain',
        skills: ['Estrategia empresarial', 'Innovation consulting', 'Design Thinking', 'Lean Startup', 'Public speaking', 'Fundraising'],
        experience: [
            { title: 'Consultora de innovación', company: 'InnovaHub', startYear: 2021, endYear: null, current: true, description: 'Consultoría estratégica para startups y corporaciones' },
            { title: 'Co-fundadora', company: 'NeuroBridge (startup)', startYear: 2019, endYear: 2021, current: false, description: 'Plataforma de neurodiversidad en el trabajo' },
        ],
        education: [
            { degree: 'MBA', institution: 'ESADE', year: 2019, field: 'Business' },
            { degree: 'Grado en Ingeniería Industrial', institution: 'UPC', year: 2017, field: 'Ingeniería' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 50000,
            salaryMax: 80000,
            locations: ['Barcelona', 'Madrid', 'Remote'],
            roles: ['Consultora', 'Directora de innovación', 'Strategy Lead'],
            industries: ['Consultoría', 'Technology', 'Education'],
        },
        privacy: { visibleInSearch: true, showRealName: true, shareDiagnosis: true, shareTherapistContact: true, shareAssessmentDetails: true },
        assessment: {
            completed: true,
            completedAt: '2026-01-18T13:00:00Z',
            strengths: ['rapid_ideation', 'cross_domain_thinking', 'charisma', 'hyperfocus_on_passion_projects'],
            challenges: ['routine_tasks', 'follow_through', 'bureaucracy', 'understimulation'],
            score: 90,
            technicalSkills: ['Design Thinking', 'Strategy', 'Public Speaking'],
            softSkills: ['leadership', 'vision', 'communication', 'creativity'],
            workStyle: { preferredHours: 'flexible', environment: 'dynamic', collaboration: 'leadership' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 18, matchesReceived: 6, applicationsSubmitted: 0 },
    },

    // ─── TOC (Trastorno Obsesivo-Compulsivo) (1 perfil) ────────
    {
        email: 'alberto.jimenez@seed.diversia.com',
        firstName: 'Alberto',
        lastName: 'Jiménez',
        diagnoses: ['encrypted:TOC'],
        accommodationsNeeded: 'encrypted:understanding_rituals,flexibility_for_compulsions,reduced_time_pressure,private_workspace',
        experienceYears: 5,
        bio: 'Contable y auditor con TOC. Mi necesidad de verificación constante es una ventaja en auditoría: detecto errores que otros pasan por alto. Necesito un entorno comprensivo con mis rutinas.',
        location: 'Madrid, Spain',
        skills: ['Contabilidad', 'Auditoría', 'SAP', 'Excel avanzado', 'Normativa fiscal', 'IFRS'],
        experience: [
            { title: 'Auditor junior', company: 'AuditPro', startYear: 2022, endYear: null, current: true, description: 'Auditoría financiera y compliance' },
            { title: 'Contable', company: 'Gestión Fiscal SL', startYear: 2020, endYear: 2022, current: false, description: 'Contabilidad general y fiscal' },
        ],
        education: [
            { degree: 'Grado en ADE', institution: 'Universidad Autónoma de Madrid', year: 2020, field: 'Economía' },
        ],
        preferences: {
            workMode: 'hybrid',
            salaryMin: 30000,
            salaryMax: 42000,
            locations: ['Madrid'],
            roles: ['Auditor', 'Contable', 'Controller financiero'],
            industries: ['Finance', 'Consultoría', 'Administración'],
        },
        privacy: { visibleInSearch: true, showRealName: false, shareDiagnosis: false, shareTherapistContact: false, shareAssessmentDetails: false },
        assessment: {
            completed: true,
            completedAt: '2026-02-11T11:00:00Z',
            strengths: ['error_detection', 'thoroughness', 'verification', 'compliance_adherence'],
            challenges: ['time_pressure', 'interruptions_during_verification', 'accepting_good_enough'],
            score: 84,
            technicalSkills: ['SAP', 'Excel', 'IFRS'],
            softSkills: ['precision', 'integrity', 'methodical_approach'],
            workStyle: { preferredHours: 'fixed', environment: 'private_office', collaboration: 'structured' },
        },
        metadata: { lastLogin: new Date().toISOString(), profileViews: 4, matchesReceived: 2, applicationsSubmitted: 1 },
    },
]
