// ═══════════════════════════════════════════════════════════════════
// EMPRESAS — 10 empresas de sectores variados
// Dominio: @seed.diversia.com (NUNCA mezclar con datos reales)
// Abanico laboral completo: tech, restauración, alimentación,
// servicios generales, salud, educación, retail, logística, ONG, consultoría
// ═══════════════════════════════════════════════════════════════════

export interface CompanyProfile {
    email: string
    name: string
    industry: string
    size: string
    location: string
    website: string
    description: string
    diversityCommitment: string
    neurodiversityPrograms: Array<{ name: string; description: string; type: string }>
    subscriptionPlan: string
    metadata: Record<string, unknown>
    jobs: JobProfile[]
}

export interface JobProfile {
    id: string
    title: string
    description: string
    status: 'PUBLISHED' | 'DRAFT' | 'CLOSED'
    skills: string[]
    accommodations: string[]
    salaryRange: string
    workMode: string
    visibility: string
    location: string
    benefits: Array<{ name: string; value: string }>
    teamSize: string
    reportingStructure: string
    inclusivityScore: number
    inclusivityAnalysis: { score: number; strengths: string[]; improvements: string[]; analyzedAt: string }
}

export const companyProfiles: CompanyProfile[] = [
    // ─── 1. Tecnología ──────────────────────────────────────────
    {
        email: 'neuratech@seed.diversia.com',
        name: 'NeuraTech Solutions',
        industry: 'Technology',
        size: '50-200',
        location: 'Barcelona, Spain',
        website: 'https://neuratech.seed',
        description: 'Empresa tecnológica especializada en IA accesible y herramientas para neurodiversidad. Cultura remote-first y flexible.',
        diversityCommitment: 'Nuestro equipo es 40% neurodivergente. La diversidad cognitiva es nuestra ventaja competitiva.',
        neurodiversityPrograms: [
            { name: 'Quiet Spaces', description: 'Espacios sensoriales adaptados en oficina', type: 'accommodation' },
            { name: 'Flex Schedule', description: 'Horarios 100% flexibles', type: 'policy' },
            { name: 'NeuroMentor', description: 'Programa de mentoría para empleados neurodivergentes', type: 'mentoring' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 5, averageTimeToHire: 12 },
        jobs: [
            {
                id: 'job_neuratech_frontend',
                title: 'Frontend Developer (React/Next.js)',
                description: 'Buscamos desarrollador frontend para nuestro equipo de producto. Entorno async-first, horarios flexibles y accommodations disponibles.',
                status: 'PUBLISHED',
                skills: ['React', 'Next.js', 'TypeScript', 'CSS', 'Testing'],
                accommodations: ['flexible_schedule', 'remote_work', 'noise_cancelling', 'written_instructions', 'async_communication'],
                salaryRange: '35000-55000 EUR',
                workMode: 'remote',
                visibility: 'public',
                location: 'Remote (Spain)',
                benefits: [
                    { name: 'Horario flexible', value: 'Elige tu propio horario' },
                    { name: 'Oficina sensorial', value: 'Espacios adaptados disponibles' },
                    { name: 'Días de salud mental', value: '5 días extra al año' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Flat, async-first',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['flexible_schedule', 'accommodation_listed', 'inclusive_language', 'mentoring'], improvements: ['could_add_salary_transparency'], analyzedAt: '2026-02-15T10:00:00Z' },
            },
            {
                id: 'job_neuratech_data',
                title: 'Data Scientist (ML/Python)',
                description: 'Rol de data science con onboarding estructurado y rutinas predecibles. Valoramos pensadores sistemáticos.',
                status: 'PUBLISHED',
                skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas'],
                accommodations: ['predictable_schedule', 'written_instructions', 'quiet_workspace', 'structured_meetings'],
                salaryRange: '40000-60000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Onboarding estructurado', value: 'Programa de 4 semanas con guías escritas' },
                    { name: 'Rutina predecible', value: 'Calendario fijo de reuniones' },
                    { name: 'Sala sensorial', value: 'Disponible en oficina' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Jerarquía clara con 1:1 semanal',
                inclusivityScore: 92,
                inclusivityAnalysis: { score: 92, strengths: ['structured_environment', 'explicit_accommodations', 'predictable_culture'], improvements: [], analyzedAt: '2026-02-16T11:00:00Z' },
            },
            {
                id: 'job_neuratech_backend',
                title: 'Backend Developer (Java/Spring)',
                description: 'Desarrollo de microservicios. Equipo pequeño, comunicación asíncrona, código limpio como prioridad.',
                status: 'PUBLISHED',
                skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'AWS'],
                accommodations: ['remote_work', 'async_communication', 'flexible_schedule', 'private_workspace'],
                salaryRange: '38000-58000 EUR',
                workMode: 'remote',
                visibility: 'public',
                location: 'Remote (Spain)',
                benefits: [
                    { name: 'Remote 100%', value: 'Trabaja desde donde quieras' },
                    { name: 'Presupuesto de formación', value: '1500 EUR/año' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Flat con tech lead',
                inclusivityScore: 85,
                inclusivityAnalysis: { score: 85, strengths: ['remote_first', 'async_communication', 'small_team'], improvements: ['add_mentoring_program'], analyzedAt: '2026-02-17T09:00:00Z' },
            },
        ],
    },

    // ─── 2. Restauración ────────────────────────────────────────
    {
        email: 'cocina.inclusiva@seed.diversia.com',
        name: 'Cocina Inclusiva S.L.',
        industry: 'Restauración',
        size: '10-50',
        location: 'Valencia, Spain',
        website: 'https://cocinainclusive.seed',
        description: 'Grupo de restaurantes comprometido con la inclusión laboral. Nuestras cocinas están adaptadas y nuestros equipos formados en neurodiversidad.',
        diversityCommitment: 'Creemos que la diversidad en cocina crea platos únicos. Adaptamos puestos y formamos equipos comprensivos.',
        neurodiversityPrograms: [
            { name: 'Cocina Visual', description: 'Recetas con pictogramas y pasos visuales', type: 'accommodation' },
            { name: 'Buddy System', description: 'Compañero de apoyo durante el primer mes', type: 'mentoring' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 3, averageTimeToHire: 7 },
        jobs: [
            {
                id: 'job_cocina_reposteria',
                title: 'Chef de Repostería',
                description: 'Buscamos repostero/a creativo/a. Cocina con recetas visuales, ambiente de equipo comprensivo y descansos flexibles.',
                status: 'PUBLISHED',
                skills: ['Repostería creativa', 'Pastelería', 'Decoración', 'APPCC'],
                accommodations: ['visual_recipes', 'flexible_breaks', 'buddy_system', 'structured_tasks'],
                salaryRange: '22000-30000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Comidas incluidas', value: 'Desayuno y comida' },
                    { name: 'Recetas visuales', value: 'Pictogramas y pasos claros' },
                    { name: 'Descansos flexibles', value: 'Pausas cuando las necesites' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Jefe de cocina con apoyo de buddy',
                inclusivityScore: 82,
                inclusivityAnalysis: { score: 82, strengths: ['visual_aids', 'buddy_system', 'flexible_breaks'], improvements: ['add_noise_reduction'], analyzedAt: '2026-02-18T09:00:00Z' },
            },
            {
                id: 'job_cocina_sala',
                title: 'Camarero/a de Sala (Turno mañana)',
                description: 'Servicio en sala con turno fijo de mañana. Formación completa y ambiente comprensivo. No se requiere experiencia.',
                status: 'PUBLISHED',
                skills: ['Atención al cliente', 'TPV', 'Servicio de sala', 'Trabajo en equipo'],
                accommodations: ['fixed_schedule', 'structured_training', 'buddy_system', 'clear_tasks'],
                salaryRange: '18000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Turno fijo', value: 'Solo mañanas (7:00-15:00)' },
                    { name: 'Formación pagada', value: '2 semanas de formación remunerada' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Maître con supervisión cercana',
                inclusivityScore: 75,
                inclusivityAnalysis: { score: 75, strengths: ['fixed_schedule', 'training_provided', 'buddy_system'], improvements: ['add_sensory_accommodations', 'reduce_multitasking'], analyzedAt: '2026-02-18T10:00:00Z' },
            },
        ],
    },

    // ─── 3. Alimentación ────────────────────────────────────────
    {
        email: 'nutridiversa@seed.diversia.com',
        name: 'NutriDiversa',
        industry: 'Alimentación',
        size: '200-500',
        location: 'Zaragoza, Spain',
        website: 'https://nutridiversa.seed',
        description: 'Empresa de producción y distribución alimentaria con políticas de inclusión pioneras en el sector.',
        diversityCommitment: 'La precisión y el detalle que aportan perfiles neurodivergentes son clave en nuestro control de calidad.',
        neurodiversityPrograms: [
            { name: 'Protocolo Visual', description: 'Todos los procesos documentados con apoyo visual', type: 'accommodation' },
            { name: 'Horario Predecible', description: 'Turnos fijos sin rotaciones inesperadas', type: 'policy' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 4, averageTimeToHire: 10 },
        jobs: [
            {
                id: 'job_nutri_calidad',
                title: 'Técnico de Control de Calidad Alimentaria',
                description: 'Control de calidad en línea de producción. Trabajo metódico, protocolos claros y ambiente estructurado.',
                status: 'PUBLISHED',
                skills: ['Control de calidad', 'APPCC', 'ISO 22000', 'Análisis microbiológico', 'Documentación técnica'],
                accommodations: ['structured_environment', 'visual_protocols', 'predictable_schedule', 'minimal_social_demands'],
                salaryRange: '28000-38000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Turno fijo', value: 'Sin rotaciones' },
                    { name: 'Protocolos visuales', value: 'Documentación con apoyo gráfico' },
                    { name: 'Entorno controlado', value: 'Laboratorio con clima y luz regulados' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Responsable de calidad con reuniones semanales',
                inclusivityScore: 90,
                inclusivityAnalysis: { score: 90, strengths: ['structured_tasks', 'visual_protocols', 'predictable_environment'], improvements: [], analyzedAt: '2026-02-19T08:00:00Z' },
            },
            {
                id: 'job_nutri_logistica',
                title: 'Coordinador/a de Logística Alimentaria',
                description: 'Gestión de la cadena de distribución. Trabajo con sistemas informáticos, planificación y trazabilidad.',
                status: 'PUBLISHED',
                skills: ['Logística', 'SAP', 'Gestión de inventarios', 'Trazabilidad', 'Excel'],
                accommodations: ['written_instructions', 'predictable_routine', 'quiet_office', 'structured_meetings'],
                salaryRange: '30000-40000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Horario regular', value: 'L-V 8:00-16:00' },
                    { name: 'Oficina tranquila', value: 'Separada de producción' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Director de operaciones',
                inclusivityScore: 78,
                inclusivityAnalysis: { score: 78, strengths: ['predictable_routine', 'quiet_office'], improvements: ['add_visual_aids', 'more_flexible_breaks'], analyzedAt: '2026-02-19T09:00:00Z' },
            },
        ],
    },

    // ─── 4. Servicios Generales ─────────────────────────────────
    {
        email: 'serviplus@seed.diversia.com',
        name: 'ServiPlus Inclusivo',
        industry: 'Servicios Generales',
        size: '50-200',
        location: 'Madrid, Spain',
        website: 'https://serviplus.seed',
        description: 'Empresa de servicios de mantenimiento, limpieza y jardinería con compromiso real de inclusión laboral neurodivergente.',
        diversityCommitment: 'Ofrecemos puestos adaptados con tareas claras, rutinas predecibles y supervisión comprensiva.',
        neurodiversityPrograms: [
            { name: 'Tareas Claras', description: 'Lista visual de tareas diarias para cada puesto', type: 'accommodation' },
            { name: 'Supervisor de Apoyo', description: 'Supervisores formados en neurodiversidad', type: 'training' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 6, averageTimeToHire: 5 },
        jobs: [
            {
                id: 'job_servi_mantenimiento',
                title: 'Técnico de Mantenimiento General',
                description: 'Mantenimiento de instalaciones. Variedad de tareas (electricidad, fontanería, climatización). Autonomía y movimiento.',
                status: 'PUBLISHED',
                skills: ['Electricidad', 'Fontanería', 'Climatización', 'Mantenimiento preventivo', 'PRL'],
                accommodations: ['varied_tasks', 'movement_allowed', 'clear_task_lists', 'flexible_breaks'],
                salaryRange: '24000-35000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Variedad de tareas', value: 'Nunca dos días iguales' },
                    { name: 'Autonomía', value: 'Organiza tu ruta de trabajo' },
                    { name: 'Formación continua', value: 'Cursos de PRL pagados' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Jefe de equipo accesible',
                inclusivityScore: 80,
                inclusivityAnalysis: { score: 80, strengths: ['varied_tasks', 'autonomy', 'movement'], improvements: ['add_written_instructions'], analyzedAt: '2026-02-20T08:00:00Z' },
            },
            {
                id: 'job_servi_jardineria',
                title: 'Jardinero/a',
                description: 'Mantenimiento de jardines y zonas verdes. Trabajo al aire libre, tareas repetitivas y tangibles. Ideal para perfiles que buscan actividad física y resultados visibles.',
                status: 'PUBLISHED',
                skills: ['Jardinería', 'Poda', 'Riego', 'Maquinaria de jardín', 'Conocimientos botánicos'],
                accommodations: ['outdoor_work', 'physical_activity', 'visual_task_list', 'predictable_routine', 'minimal_social_demands'],
                salaryRange: '18000-24000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Trabajo al aire libre', value: '100% exterior' },
                    { name: 'Rutina estable', value: 'Mismas zonas cada semana' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de zona',
                inclusivityScore: 83,
                inclusivityAnalysis: { score: 83, strengths: ['outdoor_environment', 'physical_work', 'predictable_routine', 'tangible_results'], improvements: ['weather_contingency_plan'], analyzedAt: '2026-02-20T09:00:00Z' },
            },
            {
                id: 'job_servi_limpieza',
                title: 'Profesional de Limpieza',
                description: 'Limpieza de oficinas en turno de mañana. Tareas con checklist visual, ritmo propio, ambiente tranquilo sin público.',
                status: 'PUBLISHED',
                skills: ['Limpieza profesional', 'Productos de limpieza', 'Organización', 'PRL'],
                accommodations: ['visual_checklist', 'own_pace', 'no_public_facing', 'fixed_schedule', 'quiet_environment'],
                salaryRange: '16000-20000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Turno mañana', value: '6:00-14:00' },
                    { name: 'Sin atención al público', value: 'Trabajo en espacios vacíos' },
                    { name: 'Checklist visual', value: 'Lista de tareas con fotos' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de zona con check-in diario',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['no_public_facing', 'visual_checklist', 'quiet', 'own_pace'], improvements: [], analyzedAt: '2026-02-20T10:00:00Z' },
            },
        ],
    },

    // ─── 5. Salud ───────────────────────────────────────────────
    {
        email: 'clinica.neurovida@seed.diversia.com',
        name: 'Clínica NeuroVida',
        industry: 'Salud',
        size: '10-50',
        location: 'Barcelona, Spain',
        website: 'https://neurovida.seed',
        description: 'Clínica especializada en neurología y salud mental con enfoque inclusivo en la contratación.',
        diversityCommitment: 'Como clínica especializada en neurodiversidad, predicamos con el ejemplo en nuestras contrataciones.',
        neurodiversityPrograms: [
            { name: 'Adaptación Sensorial', description: 'Espacios de descanso con iluminación regulable', type: 'accommodation' },
            { name: 'Formación Interna', description: 'Talleres mensuales sobre neurodiversidad', type: 'training' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 2, averageTimeToHire: 14 },
        jobs: [
            {
                id: 'job_clinica_admin',
                title: 'Auxiliar Administrativo/a Sanitario',
                description: 'Gestión de citas, archivo y documentación clínica. Trabajo metódico con sistemas informáticos en entorno tranquilo.',
                status: 'PUBLISHED',
                skills: ['Administración sanitaria', 'Gestión de citas', 'Archivo clínico', 'Ofimática', 'Atención telefónica'],
                accommodations: ['structured_tasks', 'quiet_office', 'written_procedures', 'predictable_routine'],
                salaryRange: '20000-26000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Entorno tranquilo', value: 'Oficina separada de consultas' },
                    { name: 'Procedimientos escritos', value: 'Manual completo de tareas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Coordinador administrativo',
                inclusivityScore: 84,
                inclusivityAnalysis: { score: 84, strengths: ['quiet_environment', 'written_procedures', 'structured'], improvements: ['add_flexible_schedule'], analyzedAt: '2026-02-21T08:00:00Z' },
            },
            {
                id: 'job_clinica_auxiliar',
                title: 'Auxiliar de Enfermería',
                description: 'Apoyo en consultas neurológicas. Tareas claras con protocolos escritos. Formación en neurodiversidad incluida.',
                status: 'PUBLISHED',
                skills: ['Enfermería auxiliar', 'Protocolos sanitarios', 'Atención al paciente', 'Documentación clínica'],
                accommodations: ['clear_protocols', 'structured_shifts', 'buddy_system', 'advance_notice_of_changes'],
                salaryRange: '22000-28000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Protocolos claros', value: 'Guías paso a paso para cada procedimiento' },
                    { name: 'Turnos fijos', value: 'Sin rotaciones inesperadas' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Enfermera jefe',
                inclusivityScore: 79,
                inclusivityAnalysis: { score: 79, strengths: ['clear_protocols', 'training_provided'], improvements: ['add_sensory_breaks', 'reduce_social_demands'], analyzedAt: '2026-02-21T09:00:00Z' },
            },
        ],
    },

    // ─── 6. Educación ───────────────────────────────────────────
    {
        email: 'academia.brillante@seed.diversia.com',
        name: 'Academia Brillante',
        industry: 'Educación',
        size: '10-50',
        location: 'Madrid, Spain',
        website: 'https://brillante.seed',
        description: 'Centro educativo inclusivo que celebra la neurodiversidad tanto en alumnado como en profesorado.',
        diversityCommitment: 'Nuestros profesores neurodivergentes son modelos a seguir para nuestros estudiantes.',
        neurodiversityPrograms: [
            { name: 'Aula Sensorial', description: 'Espacios de regulación para profesorado y alumnado', type: 'accommodation' },
            { name: 'Co-docencia', description: 'Dos profesores por aula para reducir carga', type: 'policy' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 2, averageTimeToHire: 21 },
        jobs: [
            {
                id: 'job_academia_docente',
                title: 'Profesor/a de Ciencias (Secundaria)',
                description: 'Docencia en instituto inclusivo. Grupos reducidos, co-docencia y programación flexible.',
                status: 'PUBLISHED',
                skills: ['Docencia', 'Ciencias', 'Pedagogía inclusiva', 'Programación didáctica', 'TIC educativas'],
                accommodations: ['co_teaching', 'reduced_class_size', 'preparation_time', 'flexible_methodology'],
                salaryRange: '28000-38000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Grupos reducidos', value: 'Máximo 15 alumnos' },
                    { name: 'Co-docencia', value: 'Siempre con otro profesor de apoyo' },
                    { name: 'Formación continua', value: 'Especialización pagada en neurodiversidad' },
                ],
                teamSize: '10-20',
                reportingStructure: 'Jefe de departamento',
                inclusivityScore: 87,
                inclusivityAnalysis: { score: 87, strengths: ['reduced_groups', 'co_teaching', 'flexible_methodology'], improvements: ['add_sensory_room_for_staff'], analyzedAt: '2026-02-22T08:00:00Z' },
            },
            {
                id: 'job_academia_apoyo',
                title: 'Especialista en Apoyo Educativo',
                description: 'Diseño de adaptaciones curriculares y apoyo a alumnado neurodivergente. Imprescindible empatía y creatividad.',
                status: 'PUBLISHED',
                skills: ['Educación especial', 'Adaptaciones curriculares', 'Psicopedagogía', 'Materiales adaptados', 'Comunicación aumentativa'],
                accommodations: ['flexible_schedule', 'quiet_office', 'autonomy', 'written_communication'],
                salaryRange: '26000-34000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Horario flexible', value: 'Parte presencial, parte remoto' },
                    { name: 'Despacho propio', value: 'Espacio tranquilo de trabajo' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Departamento de orientación',
                inclusivityScore: 91,
                inclusivityAnalysis: { score: 91, strengths: ['flexibility', 'quiet_space', 'autonomy', 'purpose_driven'], improvements: [], analyzedAt: '2026-02-22T09:00:00Z' },
            },
        ],
    },

    // ─── 7. Retail / Comercio ───────────────────────────────────
    {
        email: 'tiendaparatodos@seed.diversia.com',
        name: 'TiendaParaTodos',
        industry: 'Retail',
        size: '200-500',
        location: 'Barcelona, Spain',
        website: 'https://tiendaparatodos.seed',
        description: 'Cadena de tiendas con política de contratación inclusiva y puestos adaptados a distintos perfiles cognitivos.',
        diversityCommitment: 'Cada puesto está diseñado pensando en las fortalezas, no en las limitaciones.',
        neurodiversityPrograms: [
            { name: 'Puesto a Medida', description: 'Adaptamos tareas según el perfil de cada persona', type: 'accommodation' },
            { name: 'Hora Tranquila', description: 'Hora sin música ni anuncios para empleados y clientes', type: 'sensory' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 8, averageTimeToHire: 7 },
        jobs: [
            {
                id: 'job_tienda_reponedor',
                title: 'Reponedor/a (Turno nocturno)',
                description: 'Reposición de productos en horario nocturno sin público. Tareas claras, ritmo propio y ambiente tranquilo.',
                status: 'PUBLISHED',
                skills: ['Reposición', 'Organización', 'Gestión de almacén', 'Inventario básico'],
                accommodations: ['no_public_facing', 'predictable_tasks', 'own_pace', 'visual_planogram', 'quiet_environment'],
                salaryRange: '18000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Sin atención al público', value: 'Turno nocturno (22:00-6:00)' },
                    { name: 'Tareas claras', value: 'Planograma visual para cada pasillo' },
                    { name: 'Plus nocturno', value: 'Complemento por nocturnidad' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Encargado de noche',
                inclusivityScore: 89,
                inclusivityAnalysis: { score: 89, strengths: ['no_customers', 'visual_guides', 'quiet', 'predictable'], improvements: ['offer_day_shift_option'], analyzedAt: '2026-02-23T08:00:00Z' },
            },
            {
                id: 'job_tienda_visual',
                title: 'Visual Merchandiser',
                description: 'Diseño de escaparates y espacios comerciales. Trabajo creativo y visual con planificación anticipada.',
                status: 'PUBLISHED',
                skills: ['Visual merchandising', 'Diseño de espacios', 'Creatividad', 'Planificación', 'Fotografía'],
                accommodations: ['creative_freedom', 'advance_planning', 'own_workspace', 'reduced_meetings'],
                salaryRange: '24000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Libertad creativa', value: 'Diseña los espacios a tu manera' },
                    { name: 'Planificación anticipada', value: 'Calendario mensual de escaparates' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de imagen',
                inclusivityScore: 81,
                inclusivityAnalysis: { score: 81, strengths: ['creative_freedom', 'visual_work', 'advance_planning'], improvements: ['add_quiet_workspace'], analyzedAt: '2026-02-23T09:00:00Z' },
            },
        ],
    },

    // ─── 8. Logística ───────────────────────────────────────────
    {
        email: 'logiaccess@seed.diversia.com',
        name: 'LogiAccess',
        industry: 'Logística',
        size: '200-500',
        location: 'Bilbao, Spain',
        website: 'https://logiaccess.seed',
        description: 'Operador logístico con programa de inclusión para perfiles neurodivergentes en almacén y gestión.',
        diversityCommitment: 'La precisión y consistencia de nuestros empleados neurodivergentes ha mejorado un 23% la eficiencia en almacén.',
        neurodiversityPrograms: [
            { name: 'WMS Adaptado', description: 'Interfaz de almacén simplificada y visual', type: 'technology' },
            { name: 'Zona Calma', description: 'Espacio de regulación sensorial en almacén', type: 'accommodation' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 5, averageTimeToHire: 6 },
        jobs: [
            {
                id: 'job_logi_almacen',
                title: 'Operario/a de Almacén (Picking)',
                description: 'Preparación de pedidos con sistema WMS visual. Trabajo metódico, rutinas claras y ambiente controlado.',
                status: 'PUBLISHED',
                skills: ['Picking', 'WMS', 'Gestión de inventarios', 'Carretilla elevadora', 'Organización'],
                accommodations: ['visual_wms', 'structured_tasks', 'predictable_routine', 'sensory_zone', 'clear_expectations'],
                salaryRange: '18000-24000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Bilbao, Spain',
                benefits: [
                    { name: 'WMS visual', value: 'Sistema con iconos y colores' },
                    { name: 'Zona calma', value: 'Espacio de regulación disponible' },
                    { name: 'Turno fijo', value: 'Sin rotaciones' },
                ],
                teamSize: '10-20',
                reportingStructure: 'Jefe de turno con formación inclusiva',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['visual_system', 'sensory_zone', 'predictable', 'structured'], improvements: ['reduce_noise_levels'], analyzedAt: '2026-02-24T08:00:00Z' },
            },
            {
                id: 'job_logi_inventarios',
                title: 'Gestión de Inventarios',
                description: 'Control de stock con SAP. Trabajo analítico, independiente y basado en datos. Oficina tranquila separada de almacén.',
                status: 'PUBLISHED',
                skills: ['Gestión de inventarios', 'SAP', 'Excel avanzado', 'Análisis de datos', 'Trazabilidad'],
                accommodations: ['quiet_office', 'data_driven_work', 'minimal_social_demands', 'written_communication'],
                salaryRange: '26000-34000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Bilbao, Spain',
                benefits: [
                    { name: 'Oficina separada', value: 'Fuera de la zona de almacén' },
                    { name: 'Trabajo independiente', value: 'Análisis de datos sin interrupciones' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de operaciones',
                inclusivityScore: 83,
                inclusivityAnalysis: { score: 83, strengths: ['quiet', 'independent', 'data_focused'], improvements: ['add_flexible_hours'], analyzedAt: '2026-02-24T09:00:00Z' },
            },
        ],
    },

    // ─── 9. ONG / Sector Social ─────────────────────────────────
    {
        email: 'fundacion.puentes@seed.diversia.com',
        name: 'Fundación Puentes',
        industry: 'ONG / Sector Social',
        size: '10-50',
        location: 'Granada, Spain',
        website: 'https://puentes.seed',
        description: 'ONG dedicada a la inclusión social y laboral de personas neurodivergentes y en riesgo de exclusión.',
        diversityCommitment: 'Nuestra misión ES la inclusión. El 60% de nuestro equipo son personas neurodivergentes.',
        neurodiversityPrograms: [
            { name: 'Trabajo con Propósito', description: 'Cada puesto tiene impacto social directo y visible', type: 'culture' },
            { name: 'Flex Total', description: 'Adaptación total del puesto a la persona', type: 'accommodation' },
        ],
        subscriptionPlan: 'free',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 4, averageTimeToHire: 10 },
        jobs: [
            {
                id: 'job_ong_educador',
                title: 'Educador/a Social',
                description: 'Acompañamiento a personas en riesgo de exclusión. Empatía, comunicación y trabajo en equipo. Flexibilidad total.',
                status: 'PUBLISHED',
                skills: ['Educación social', 'Mediación', 'Intervención social', 'Dinamización', 'Trabajo social'],
                accommodations: ['flexible_schedule', 'reduced_bureaucracy', 'verbal_reports', 'meaningful_work'],
                salaryRange: '22000-30000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Horario flexible', value: 'Adapta tu jornada a tus necesidades' },
                    { name: 'Impacto social', value: 'Tu trabajo cambia vidas' },
                    { name: 'Informes verbales', value: 'Opción de dictar informes en vez de escribirlos' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Coordinador de proyectos',
                inclusivityScore: 94,
                inclusivityAnalysis: { score: 94, strengths: ['flexibility', 'meaningful_work', 'verbal_reporting', 'inclusive_culture'], improvements: [], analyzedAt: '2026-02-25T08:00:00Z' },
            },
            {
                id: 'job_ong_coordinador',
                title: 'Coordinador/a de Proyectos Sociales',
                description: 'Gestión de proyectos de inclusión laboral. Planificación, seguimiento y evaluación de programas.',
                status: 'PUBLISHED',
                skills: ['Gestión de proyectos', 'Planificación', 'Evaluación de impacto', 'Redacción de memorias', 'Subvenciones'],
                accommodations: ['structured_goals', 'written_communication', 'flexible_deadlines', 'quiet_office'],
                salaryRange: '28000-36000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Teletrabajo parcial', value: '3 días remoto, 2 presencial' },
                    { name: 'Objetivos claros', value: 'Evaluación por resultados, no por horas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Director de la fundación',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['results_based', 'flexibility', 'clear_objectives'], improvements: ['add_project_management_tools'], analyzedAt: '2026-02-25T09:00:00Z' },
            },
        ],
    },

    // ─── 10. Consultoría D&I ────────────────────────────────────
    {
        email: 'diversa.consulting@seed.diversia.com',
        name: 'Diversa Consulting',
        industry: 'Consultoría',
        size: '10-50',
        location: 'Barcelona, Spain',
        website: 'https://diversaconsulting.seed',
        description: 'Consultora especializada en diversidad e inclusión, con foco en neurodiversidad en el ámbito laboral.',
        diversityCommitment: 'Somos la prueba viva de que la neurodiversidad es una ventaja empresarial.',
        neurodiversityPrograms: [
            { name: 'Walk the Talk', description: 'Aplicamos internamente todo lo que asesoramos', type: 'culture' },
            { name: 'Flex+', description: 'Máxima flexibilidad: horario, lugar, herramientas', type: 'policy' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 3, averageTimeToHire: 18 },
        jobs: [
            {
                id: 'job_diversa_consultor',
                title: 'Consultor/a de Neurodiversidad Laboral',
                description: 'Asesoramiento a empresas en adaptación de puestos, formación de equipos y políticas de inclusión.',
                status: 'PUBLISHED',
                skills: ['Consultoría D&I', 'Formación', 'Neurodiversidad', 'Accesibilidad', 'Gestión del cambio'],
                accommodations: ['flexible_schedule', 'remote_work', 'autonomy', 'reduced_admin_tasks', 'intellectual_challenge'],
                salaryRange: '35000-50000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Autonomía total', value: 'Gestiona tus proyectos a tu manera' },
                    { name: 'Impacto real', value: 'Cambias la cultura de empresas' },
                    { name: 'Formación continua', value: 'Conferencias y certificaciones pagadas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Partner responsable',
                inclusivityScore: 96,
                inclusivityAnalysis: { score: 96, strengths: ['maximum_flexibility', 'autonomy', 'meaningful_work', 'intellectual_challenge', 'walk_the_talk'], improvements: [], analyzedAt: '2026-02-26T08:00:00Z' },
            },
            {
                id: 'job_diversa_formador',
                title: 'Formador/a en Neurodiversidad',
                description: 'Diseño e impartición de formaciones sobre neurodiversidad para empresas. Creatividad y habilidades comunicativas.',
                status: 'PUBLISHED',
                skills: ['Formación', 'Diseño instruccional', 'Presentaciones', 'Neurodiversidad', 'Facilitación de grupos'],
                accommodations: ['advance_planning', 'creative_freedom', 'flexible_schedule', 'own_teaching_style'],
                salaryRange: '30000-42000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Libertad creativa', value: 'Diseña tus propias formaciones' },
                    { name: 'Planificación anticipada', value: 'Calendario trimestral de formaciones' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de formación',
                inclusivityScore: 93,
                inclusivityAnalysis: { score: 93, strengths: ['creative_freedom', 'advance_planning', 'meaningful', 'flexible'], improvements: ['add_co_facilitation_option'], analyzedAt: '2026-02-26T09:00:00Z' },
            },
        ],
    },
]
