// ═══════════════════════════════════════════════════════════════════
// EMPRESAS — 14 empresas de sectores variados
// Dominio: @seed.diversia.com (NUNCA mezclar con datos reales)
// Abanico laboral completo: tech, restauración, alimentación,
// servicios generales, salud, educación, retail, logística, ONG,
// consultoría, CONSTRUCCIÓN, TALLER MECÁNICO, VIVEROS, ARTESANÍA
// ═══════════════════════════════════════════════════════════════════

export interface CompanyProfile {
    email: string
    name: string
    industry: string
    size: string
    location: string
    website: string
    description: string
    diversityCommitment: string
    neurodiversityPrograms: Array<{ name: string; description: string; type: string }>
    subscriptionPlan: string
    metadata: Record<string, unknown>
    jobs: JobProfile[]
}

export interface JobProfile {
    id: string
    title: string
    description: string
    status: 'PUBLISHED' | 'DRAFT' | 'CLOSED'
    skills: string[]
    accommodations: string[]
    salaryRange: string
    workMode: string
    visibility: string
    location: string
    benefits: Array<{ name: string; value: string }>
    teamSize: string
    reportingStructure: string
    inclusivityScore: number
    inclusivityAnalysis: { score: number; strengths: string[]; improvements: string[]; analyzedAt: string }
}

export const companyProfiles: CompanyProfile[] = [
    // ─── 1. Tecnología ──────────────────────────────────────────
    {
        email: 'neuratech@seed.diversia.com',
        name: 'NeuraTech Solutions',
        industry: 'Technology',
        size: '50-200',
        location: 'Barcelona, Spain',
        website: 'https://neuratech.seed',
        description: 'Empresa tecnológica especializada en IA accesible y herramientas para neurodiversidad. Cultura remote-first y flexible.',
        diversityCommitment: 'Nuestro equipo es 40% neurodivergente. La diversidad cognitiva es nuestra ventaja competitiva.',
        neurodiversityPrograms: [
            { name: 'Quiet Spaces', description: 'Espacios sensoriales adaptados en oficina', type: 'accommodation' },
            { name: 'Flex Schedule', description: 'Horarios 100% flexibles', type: 'policy' },
            { name: 'NeuroMentor', description: 'Programa de mentoría para empleados neurodivergentes', type: 'mentoring' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 5, averageTimeToHire: 12 },
        jobs: [
            {
                id: 'job_neuratech_frontend',
                title: 'Frontend Developer (React/Next.js)',
                description: 'Buscamos desarrollador frontend para nuestro equipo de producto. Entorno async-first, horarios flexibles y accommodations disponibles.',
                status: 'PUBLISHED',
                skills: ['React', 'Next.js', 'TypeScript', 'CSS', 'Testing'],
                accommodations: ['flexible_schedule', 'remote_work', 'noise_cancelling', 'written_instructions', 'async_communication'],
                salaryRange: '35000-55000 EUR',
                workMode: 'remote',
                visibility: 'public',
                location: 'Remote (Spain)',
                benefits: [
                    { name: 'Horario flexible', value: 'Elige tu propio horario' },
                    { name: 'Oficina sensorial', value: 'Espacios adaptados disponibles' },
                    { name: 'Días de salud mental', value: '5 días extra al año' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Flat, async-first',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['flexible_schedule', 'accommodation_listed', 'inclusive_language', 'mentoring'], improvements: ['could_add_salary_transparency'], analyzedAt: '2026-02-15T10:00:00Z' },
            },
            {
                id: 'job_neuratech_data',
                title: 'Data Scientist (ML/Python)',
                description: 'Rol de data science con onboarding estructurado y rutinas predecibles. Valoramos pensadores sistemáticos.',
                status: 'PUBLISHED',
                skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Pandas'],
                accommodations: ['predictable_schedule', 'written_instructions', 'quiet_workspace', 'structured_meetings'],
                salaryRange: '40000-60000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Onboarding estructurado', value: 'Programa de 4 semanas con guías escritas' },
                    { name: 'Rutina predecible', value: 'Calendario fijo de reuniones' },
                    { name: 'Sala sensorial', value: 'Disponible en oficina' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Jerarquía clara con 1:1 semanal',
                inclusivityScore: 92,
                inclusivityAnalysis: { score: 92, strengths: ['structured_environment', 'explicit_accommodations', 'predictable_culture'], improvements: [], analyzedAt: '2026-02-16T11:00:00Z' },
            },
            {
                id: 'job_neuratech_backend',
                title: 'Backend Developer (Java/Spring)',
                description: 'Desarrollo de microservicios. Equipo pequeño, comunicación asíncrona, código limpio como prioridad.',
                status: 'PUBLISHED',
                skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'AWS'],
                accommodations: ['remote_work', 'async_communication', 'flexible_schedule', 'private_workspace'],
                salaryRange: '38000-58000 EUR',
                workMode: 'remote',
                visibility: 'public',
                location: 'Remote (Spain)',
                benefits: [
                    { name: 'Remote 100%', value: 'Trabaja desde donde quieras' },
                    { name: 'Presupuesto de formación', value: '1500 EUR/año' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Flat con tech lead',
                inclusivityScore: 85,
                inclusivityAnalysis: { score: 85, strengths: ['remote_first', 'async_communication', 'small_team'], improvements: ['add_mentoring_program'], analyzedAt: '2026-02-17T09:00:00Z' },
            },
        ],
    },

    // ─── 2. Restauración ────────────────────────────────────────
    {
        email: 'cocina.inclusiva@seed.diversia.com',
        name: 'Cocina Inclusiva S.L.',
        industry: 'Restauración',
        size: '10-50',
        location: 'Valencia, Spain',
        website: 'https://cocinainclusive.seed',
        description: 'Grupo de restaurantes comprometido con la inclusión laboral. Nuestras cocinas están adaptadas y nuestros equipos formados en neurodiversidad.',
        diversityCommitment: 'Creemos que la diversidad en cocina crea platos únicos. Adaptamos puestos y formamos equipos comprensivos.',
        neurodiversityPrograms: [
            { name: 'Cocina Visual', description: 'Recetas con pictogramas y pasos visuales', type: 'accommodation' },
            { name: 'Buddy System', description: 'Compañero de apoyo durante el primer mes', type: 'mentoring' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 5, candidatesHired: 6, averageTimeToHire: 7 },
        jobs: [
            {
                id: 'job_cocina_reposteria',
                title: 'Chef de Repostería',
                description: 'Buscamos repostero/a creativo/a. Cocina con recetas visuales, ambiente de equipo comprensivo y descansos flexibles.',
                status: 'PUBLISHED',
                skills: ['Repostería creativa', 'Pastelería', 'Decoración', 'APPCC'],
                accommodations: ['visual_recipes', 'flexible_breaks', 'buddy_system', 'structured_tasks'],
                salaryRange: '22000-30000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Comidas incluidas', value: 'Desayuno y comida' },
                    { name: 'Recetas visuales', value: 'Pictogramas y pasos claros' },
                    { name: 'Descansos flexibles', value: 'Pausas cuando las necesites' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Jefe de cocina con apoyo de buddy',
                inclusivityScore: 82,
                inclusivityAnalysis: { score: 82, strengths: ['visual_aids', 'buddy_system', 'flexible_breaks'], improvements: ['add_noise_reduction'], analyzedAt: '2026-02-18T09:00:00Z' },
            },
            {
                id: 'job_cocina_sala',
                title: 'Camarero/a de Sala (Turno mañana)',
                description: 'Servicio en sala con turno fijo de mañana. Formación completa y ambiente comprensivo. No se requiere experiencia.',
                status: 'PUBLISHED',
                skills: ['Atención al cliente', 'TPV', 'Servicio de sala', 'Trabajo en equipo'],
                accommodations: ['fixed_schedule', 'structured_training', 'buddy_system', 'clear_tasks'],
                salaryRange: '18000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Turno fijo', value: 'Solo mañanas (7:00-15:00)' },
                    { name: 'Formación pagada', value: '2 semanas de formación remunerada' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Maître con supervisión cercana',
                inclusivityScore: 75,
                inclusivityAnalysis: { score: 75, strengths: ['fixed_schedule', 'training_provided', 'buddy_system'], improvements: ['add_sensory_accommodations', 'reduce_multitasking'], analyzedAt: '2026-02-18T10:00:00Z' },
            },
            {
                id: 'job_cocina_ayudante',
                title: 'Ayudante de Cocina',
                description: 'Apoyo al equipo de cocina: preparación de ingredientes, mise en place, limpieza de utensilios. Tareas claras y repetitivas. No se requiere experiencia, solo ganas de aprender.',
                status: 'PUBLISHED',
                skills: ['Preparación de alimentos', 'Limpieza de cocina', 'Mise en place', 'Trabajo en equipo', 'APPCC básico'],
                accommodations: ['no_experience_required', 'visual_recipes', 'buddy_system', 'clear_repetitive_tasks', 'flexible_breaks', 'movement_allowed'],
                salaryRange: '16000-20000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Sin experiencia', value: 'Formación desde cero con buddy' },
                    { name: 'Comidas incluidas', value: 'Desayuno, comida y merienda' },
                    { name: 'Carrera profesional', value: 'Posibilidad de ascenso a cocinero/a de línea' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Cocinero/a de línea con supervisión paso a paso',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['no_barriers_to_entry', 'visual_aids', 'buddy_system', 'repetitive_structured'], improvements: ['add_ear_protection_option'], analyzedAt: '2026-02-18T11:00:00Z' },
            },
            {
                id: 'job_cocina_linea',
                title: 'Cocinero/a de Línea',
                description: 'Cocina de línea en servicio de comidas. Ritmo intenso pero predecible, tareas con timer visual. Ideal para quien busca adrenalina controlada y trabajo con las manos.',
                status: 'PUBLISHED',
                skills: ['Cocina profesional', 'Gestión de tiempos', 'APPCC', 'Trabajo bajo presión controlada', 'Emplatado'],
                accommodations: ['visual_timers', 'structured_service_rhythm', 'fixed_station', 'buddy_system', 'post_service_break'],
                salaryRange: '20000-28000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Estación fija', value: 'Tu puesto de cocina, siempre el mismo' },
                    { name: 'Timer visual', value: 'Pantalla con tiempos de comandas' },
                    { name: 'Descanso post-servicio', value: '30 min de descompresión tras cada servicio' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Jefe de partida con comunicación directa',
                inclusivityScore: 79,
                inclusivityAnalysis: { score: 79, strengths: ['predictable_rhythm', 'fixed_station', 'hands_on', 'visual_timers'], improvements: ['add_noise_reduction', 'add_sensory_break_area'], analyzedAt: '2026-02-18T12:00:00Z' },
            },
            {
                id: 'job_cocina_friegaplatos',
                title: 'Profesional de Office (Friegaplatos)',
                description: 'Limpieza de vajilla y utensilios de cocina. Trabajo rítmico, repetitivo y con resultados inmediatos. Ambiente de equipo sin atención al público.',
                status: 'PUBLISHED',
                skills: ['Limpieza profesional', 'Organización', 'Gestión de lavavajillas industrial', 'Trabajo físico'],
                accommodations: ['repetitive_rhythmic_work', 'no_public_facing', 'own_pace', 'headphones_allowed', 'visual_checklist', 'fixed_schedule'],
                salaryRange: '16000-19000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Valencia, Spain',
                benefits: [
                    { name: 'Sin público', value: 'Trabajas en la zona de office, sin clientes' },
                    { name: 'Auriculares', value: 'Puedes escuchar música/podcast mientras trabajas' },
                    { name: 'Comida incluida', value: 'Comes con el equipo de cocina' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Jefe de cocina con check-in mínimo',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['rhythmic_work', 'no_social_pressure', 'own_pace', 'music_allowed', 'immediate_results'], improvements: ['add_anti_fatigue_mats'], analyzedAt: '2026-02-18T13:00:00Z' },
            },
        ],
    },

    // ─── 3. Alimentación ────────────────────────────────────────
    {
        email: 'nutridiversa@seed.diversia.com',
        name: 'NutriDiversa',
        industry: 'Alimentación',
        size: '200-500',
        location: 'Zaragoza, Spain',
        website: 'https://nutridiversa.seed',
        description: 'Empresa de producción y distribución alimentaria con políticas de inclusión pioneras en el sector.',
        diversityCommitment: 'La precisión y el detalle que aportan perfiles neurodivergentes son clave en nuestro control de calidad.',
        neurodiversityPrograms: [
            { name: 'Protocolo Visual', description: 'Todos los procesos documentados con apoyo visual', type: 'accommodation' },
            { name: 'Horario Predecible', description: 'Turnos fijos sin rotaciones inesperadas', type: 'policy' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 4, averageTimeToHire: 10 },
        jobs: [
            {
                id: 'job_nutri_calidad',
                title: 'Técnico de Control de Calidad Alimentaria',
                description: 'Control de calidad en línea de producción. Trabajo metódico, protocolos claros y ambiente estructurado.',
                status: 'PUBLISHED',
                skills: ['Control de calidad', 'APPCC', 'ISO 22000', 'Análisis microbiológico', 'Documentación técnica'],
                accommodations: ['structured_environment', 'visual_protocols', 'predictable_schedule', 'minimal_social_demands'],
                salaryRange: '28000-38000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Turno fijo', value: 'Sin rotaciones' },
                    { name: 'Protocolos visuales', value: 'Documentación con apoyo gráfico' },
                    { name: 'Entorno controlado', value: 'Laboratorio con clima y luz regulados' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Responsable de calidad con reuniones semanales',
                inclusivityScore: 90,
                inclusivityAnalysis: { score: 90, strengths: ['structured_tasks', 'visual_protocols', 'predictable_environment'], improvements: [], analyzedAt: '2026-02-19T08:00:00Z' },
            },
            {
                id: 'job_nutri_logistica',
                title: 'Coordinador/a de Logística Alimentaria',
                description: 'Gestión de la cadena de distribución. Trabajo con sistemas informáticos, planificación y trazabilidad.',
                status: 'PUBLISHED',
                skills: ['Logística', 'SAP', 'Gestión de inventarios', 'Trazabilidad', 'Excel'],
                accommodations: ['written_instructions', 'predictable_routine', 'quiet_office', 'structured_meetings'],
                salaryRange: '30000-40000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Horario regular', value: 'L-V 8:00-16:00' },
                    { name: 'Oficina tranquila', value: 'Separada de producción' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Director de operaciones',
                inclusivityScore: 78,
                inclusivityAnalysis: { score: 78, strengths: ['predictable_routine', 'quiet_office'], improvements: ['add_visual_aids', 'more_flexible_breaks'], analyzedAt: '2026-02-19T09:00:00Z' },
            },
        ],
    },

    // ─── 4. Servicios Generales ─────────────────────────────────
    {
        email: 'serviplus@seed.diversia.com',
        name: 'ServiPlus Inclusivo',
        industry: 'Servicios Generales',
        size: '50-200',
        location: 'Madrid, Spain',
        website: 'https://serviplus.seed',
        description: 'Empresa de servicios de mantenimiento, limpieza y jardinería con compromiso real de inclusión laboral neurodivergente.',
        diversityCommitment: 'Ofrecemos puestos adaptados con tareas claras, rutinas predecibles y supervisión comprensiva.',
        neurodiversityPrograms: [
            { name: 'Tareas Claras', description: 'Lista visual de tareas diarias para cada puesto', type: 'accommodation' },
            { name: 'Supervisor de Apoyo', description: 'Supervisores formados en neurodiversidad', type: 'training' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 6, averageTimeToHire: 5 },
        jobs: [
            {
                id: 'job_servi_mantenimiento',
                title: 'Técnico de Mantenimiento General',
                description: 'Mantenimiento de instalaciones. Variedad de tareas (electricidad, fontanería, climatización). Autonomía y movimiento.',
                status: 'PUBLISHED',
                skills: ['Electricidad', 'Fontanería', 'Climatización', 'Mantenimiento preventivo', 'PRL'],
                accommodations: ['varied_tasks', 'movement_allowed', 'clear_task_lists', 'flexible_breaks'],
                salaryRange: '24000-35000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Variedad de tareas', value: 'Nunca dos días iguales' },
                    { name: 'Autonomía', value: 'Organiza tu ruta de trabajo' },
                    { name: 'Formación continua', value: 'Cursos de PRL pagados' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Jefe de equipo accesible',
                inclusivityScore: 80,
                inclusivityAnalysis: { score: 80, strengths: ['varied_tasks', 'autonomy', 'movement'], improvements: ['add_written_instructions'], analyzedAt: '2026-02-20T08:00:00Z' },
            },
            {
                id: 'job_servi_jardineria',
                title: 'Jardinero/a',
                description: 'Mantenimiento de jardines y zonas verdes. Trabajo al aire libre, tareas repetitivas y tangibles. Ideal para perfiles que buscan actividad física y resultados visibles.',
                status: 'PUBLISHED',
                skills: ['Jardinería', 'Poda', 'Riego', 'Maquinaria de jardín', 'Conocimientos botánicos'],
                accommodations: ['outdoor_work', 'physical_activity', 'visual_task_list', 'predictable_routine', 'minimal_social_demands'],
                salaryRange: '18000-24000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Trabajo al aire libre', value: '100% exterior' },
                    { name: 'Rutina estable', value: 'Mismas zonas cada semana' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de zona',
                inclusivityScore: 83,
                inclusivityAnalysis: { score: 83, strengths: ['outdoor_environment', 'physical_work', 'predictable_routine', 'tangible_results'], improvements: ['weather_contingency_plan'], analyzedAt: '2026-02-20T09:00:00Z' },
            },
            {
                id: 'job_servi_limpieza',
                title: 'Profesional de Limpieza',
                description: 'Limpieza de oficinas en turno de mañana. Tareas con checklist visual, ritmo propio, ambiente tranquilo sin público.',
                status: 'PUBLISHED',
                skills: ['Limpieza profesional', 'Productos de limpieza', 'Organización', 'PRL'],
                accommodations: ['visual_checklist', 'own_pace', 'no_public_facing', 'fixed_schedule', 'quiet_environment'],
                salaryRange: '16000-20000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Turno mañana', value: '6:00-14:00' },
                    { name: 'Sin atención al público', value: 'Trabajo en espacios vacíos' },
                    { name: 'Checklist visual', value: 'Lista de tareas con fotos' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de zona con check-in diario',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['no_public_facing', 'visual_checklist', 'quiet', 'own_pace'], improvements: [], analyzedAt: '2026-02-20T10:00:00Z' },
            },
        ],
    },

    // ─── 5. Salud ───────────────────────────────────────────────
    {
        email: 'clinica.neurovida@seed.diversia.com',
        name: 'Clínica NeuroVida',
        industry: 'Salud',
        size: '10-50',
        location: 'Barcelona, Spain',
        website: 'https://neurovida.seed',
        description: 'Clínica especializada en neurología y salud mental con enfoque inclusivo en la contratación.',
        diversityCommitment: 'Como clínica especializada en neurodiversidad, predicamos con el ejemplo en nuestras contrataciones.',
        neurodiversityPrograms: [
            { name: 'Adaptación Sensorial', description: 'Espacios de descanso con iluminación regulable', type: 'accommodation' },
            { name: 'Formación Interna', description: 'Talleres mensuales sobre neurodiversidad', type: 'training' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 2, averageTimeToHire: 14 },
        jobs: [
            {
                id: 'job_clinica_admin',
                title: 'Auxiliar Administrativo/a Sanitario',
                description: 'Gestión de citas, archivo y documentación clínica. Trabajo metódico con sistemas informáticos en entorno tranquilo.',
                status: 'PUBLISHED',
                skills: ['Administración sanitaria', 'Gestión de citas', 'Archivo clínico', 'Ofimática', 'Atención telefónica'],
                accommodations: ['structured_tasks', 'quiet_office', 'written_procedures', 'predictable_routine'],
                salaryRange: '20000-26000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Entorno tranquilo', value: 'Oficina separada de consultas' },
                    { name: 'Procedimientos escritos', value: 'Manual completo de tareas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Coordinador administrativo',
                inclusivityScore: 84,
                inclusivityAnalysis: { score: 84, strengths: ['quiet_environment', 'written_procedures', 'structured'], improvements: ['add_flexible_schedule'], analyzedAt: '2026-02-21T08:00:00Z' },
            },
            {
                id: 'job_clinica_auxiliar',
                title: 'Auxiliar de Enfermería',
                description: 'Apoyo en consultas neurológicas. Tareas claras con protocolos escritos. Formación en neurodiversidad incluida.',
                status: 'PUBLISHED',
                skills: ['Enfermería auxiliar', 'Protocolos sanitarios', 'Atención al paciente', 'Documentación clínica'],
                accommodations: ['clear_protocols', 'structured_shifts', 'buddy_system', 'advance_notice_of_changes'],
                salaryRange: '22000-28000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Protocolos claros', value: 'Guías paso a paso para cada procedimiento' },
                    { name: 'Turnos fijos', value: 'Sin rotaciones inesperadas' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Enfermera jefe',
                inclusivityScore: 79,
                inclusivityAnalysis: { score: 79, strengths: ['clear_protocols', 'training_provided'], improvements: ['add_sensory_breaks', 'reduce_social_demands'], analyzedAt: '2026-02-21T09:00:00Z' },
            },
        ],
    },

    // ─── 6. Educación ───────────────────────────────────────────
    {
        email: 'academia.brillante@seed.diversia.com',
        name: 'Academia Brillante',
        industry: 'Educación',
        size: '10-50',
        location: 'Madrid, Spain',
        website: 'https://brillante.seed',
        description: 'Centro educativo inclusivo que celebra la neurodiversidad tanto en alumnado como en profesorado.',
        diversityCommitment: 'Nuestros profesores neurodivergentes son modelos a seguir para nuestros estudiantes.',
        neurodiversityPrograms: [
            { name: 'Aula Sensorial', description: 'Espacios de regulación para profesorado y alumnado', type: 'accommodation' },
            { name: 'Co-docencia', description: 'Dos profesores por aula para reducir carga', type: 'policy' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 2, averageTimeToHire: 21 },
        jobs: [
            {
                id: 'job_academia_docente',
                title: 'Profesor/a de Ciencias (Secundaria)',
                description: 'Docencia en instituto inclusivo. Grupos reducidos, co-docencia y programación flexible.',
                status: 'PUBLISHED',
                skills: ['Docencia', 'Ciencias', 'Pedagogía inclusiva', 'Programación didáctica', 'TIC educativas'],
                accommodations: ['co_teaching', 'reduced_class_size', 'preparation_time', 'flexible_methodology'],
                salaryRange: '28000-38000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Grupos reducidos', value: 'Máximo 15 alumnos' },
                    { name: 'Co-docencia', value: 'Siempre con otro profesor de apoyo' },
                    { name: 'Formación continua', value: 'Especialización pagada en neurodiversidad' },
                ],
                teamSize: '10-20',
                reportingStructure: 'Jefe de departamento',
                inclusivityScore: 87,
                inclusivityAnalysis: { score: 87, strengths: ['reduced_groups', 'co_teaching', 'flexible_methodology'], improvements: ['add_sensory_room_for_staff'], analyzedAt: '2026-02-22T08:00:00Z' },
            },
            {
                id: 'job_academia_apoyo',
                title: 'Especialista en Apoyo Educativo',
                description: 'Diseño de adaptaciones curriculares y apoyo a alumnado neurodivergente. Imprescindible empatía y creatividad.',
                status: 'PUBLISHED',
                skills: ['Educación especial', 'Adaptaciones curriculares', 'Psicopedagogía', 'Materiales adaptados', 'Comunicación aumentativa'],
                accommodations: ['flexible_schedule', 'quiet_office', 'autonomy', 'written_communication'],
                salaryRange: '26000-34000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Madrid, Spain',
                benefits: [
                    { name: 'Horario flexible', value: 'Parte presencial, parte remoto' },
                    { name: 'Despacho propio', value: 'Espacio tranquilo de trabajo' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Departamento de orientación',
                inclusivityScore: 91,
                inclusivityAnalysis: { score: 91, strengths: ['flexibility', 'quiet_space', 'autonomy', 'purpose_driven'], improvements: [], analyzedAt: '2026-02-22T09:00:00Z' },
            },
        ],
    },

    // ─── 7. Retail / Comercio ───────────────────────────────────
    {
        email: 'tiendaparatodos@seed.diversia.com',
        name: 'TiendaParaTodos',
        industry: 'Retail',
        size: '200-500',
        location: 'Barcelona, Spain',
        website: 'https://tiendaparatodos.seed',
        description: 'Cadena de tiendas con política de contratación inclusiva y puestos adaptados a distintos perfiles cognitivos.',
        diversityCommitment: 'Cada puesto está diseñado pensando en las fortalezas, no en las limitaciones.',
        neurodiversityPrograms: [
            { name: 'Puesto a Medida', description: 'Adaptamos tareas según el perfil de cada persona', type: 'accommodation' },
            { name: 'Hora Tranquila', description: 'Hora sin música ni anuncios para empleados y clientes', type: 'sensory' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 8, averageTimeToHire: 7 },
        jobs: [
            {
                id: 'job_tienda_reponedor',
                title: 'Reponedor/a (Turno nocturno)',
                description: 'Reposición de productos en horario nocturno sin público. Tareas claras, ritmo propio y ambiente tranquilo.',
                status: 'PUBLISHED',
                skills: ['Reposición', 'Organización', 'Gestión de almacén', 'Inventario básico'],
                accommodations: ['no_public_facing', 'predictable_tasks', 'own_pace', 'visual_planogram', 'quiet_environment'],
                salaryRange: '18000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Sin atención al público', value: 'Turno nocturno (22:00-6:00)' },
                    { name: 'Tareas claras', value: 'Planograma visual para cada pasillo' },
                    { name: 'Plus nocturno', value: 'Complemento por nocturnidad' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Encargado de noche',
                inclusivityScore: 89,
                inclusivityAnalysis: { score: 89, strengths: ['no_customers', 'visual_guides', 'quiet', 'predictable'], improvements: ['offer_day_shift_option'], analyzedAt: '2026-02-23T08:00:00Z' },
            },
            {
                id: 'job_tienda_visual',
                title: 'Visual Merchandiser',
                description: 'Diseño de escaparates y espacios comerciales. Trabajo creativo y visual con planificación anticipada.',
                status: 'PUBLISHED',
                skills: ['Visual merchandising', 'Diseño de espacios', 'Creatividad', 'Planificación', 'Fotografía'],
                accommodations: ['creative_freedom', 'advance_planning', 'own_workspace', 'reduced_meetings'],
                salaryRange: '24000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Libertad creativa', value: 'Diseña los espacios a tu manera' },
                    { name: 'Planificación anticipada', value: 'Calendario mensual de escaparates' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de imagen',
                inclusivityScore: 81,
                inclusivityAnalysis: { score: 81, strengths: ['creative_freedom', 'visual_work', 'advance_planning'], improvements: ['add_quiet_workspace'], analyzedAt: '2026-02-23T09:00:00Z' },
            },
        ],
    },

    // ─── 8. Logística ───────────────────────────────────────────
    {
        email: 'logiaccess@seed.diversia.com',
        name: 'LogiAccess',
        industry: 'Logística',
        size: '200-500',
        location: 'Bilbao, Spain',
        website: 'https://logiaccess.seed',
        description: 'Operador logístico con programa de inclusión para perfiles neurodivergentes en almacén y gestión.',
        diversityCommitment: 'La precisión y consistencia de nuestros empleados neurodivergentes ha mejorado un 23% la eficiencia en almacén.',
        neurodiversityPrograms: [
            { name: 'WMS Adaptado', description: 'Interfaz de almacén simplificada y visual', type: 'technology' },
            { name: 'Zona Calma', description: 'Espacio de regulación sensorial en almacén', type: 'accommodation' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 5, averageTimeToHire: 6 },
        jobs: [
            {
                id: 'job_logi_almacen',
                title: 'Operario/a de Almacén (Picking)',
                description: 'Preparación de pedidos con sistema WMS visual. Trabajo metódico, rutinas claras y ambiente controlado.',
                status: 'PUBLISHED',
                skills: ['Picking', 'WMS', 'Gestión de inventarios', 'Carretilla elevadora', 'Organización'],
                accommodations: ['visual_wms', 'structured_tasks', 'predictable_routine', 'sensory_zone', 'clear_expectations'],
                salaryRange: '18000-24000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Bilbao, Spain',
                benefits: [
                    { name: 'WMS visual', value: 'Sistema con iconos y colores' },
                    { name: 'Zona calma', value: 'Espacio de regulación disponible' },
                    { name: 'Turno fijo', value: 'Sin rotaciones' },
                ],
                teamSize: '10-20',
                reportingStructure: 'Jefe de turno con formación inclusiva',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['visual_system', 'sensory_zone', 'predictable', 'structured'], improvements: ['reduce_noise_levels'], analyzedAt: '2026-02-24T08:00:00Z' },
            },
            {
                id: 'job_logi_inventarios',
                title: 'Gestión de Inventarios',
                description: 'Control de stock con SAP. Trabajo analítico, independiente y basado en datos. Oficina tranquila separada de almacén.',
                status: 'PUBLISHED',
                skills: ['Gestión de inventarios', 'SAP', 'Excel avanzado', 'Análisis de datos', 'Trazabilidad'],
                accommodations: ['quiet_office', 'data_driven_work', 'minimal_social_demands', 'written_communication'],
                salaryRange: '26000-34000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Bilbao, Spain',
                benefits: [
                    { name: 'Oficina separada', value: 'Fuera de la zona de almacén' },
                    { name: 'Trabajo independiente', value: 'Análisis de datos sin interrupciones' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de operaciones',
                inclusivityScore: 83,
                inclusivityAnalysis: { score: 83, strengths: ['quiet', 'independent', 'data_focused'], improvements: ['add_flexible_hours'], analyzedAt: '2026-02-24T09:00:00Z' },
            },
        ],
    },

    // ─── 9. ONG / Sector Social ─────────────────────────────────
    {
        email: 'fundacion.puentes@seed.diversia.com',
        name: 'Fundación Puentes',
        industry: 'ONG / Sector Social',
        size: '10-50',
        location: 'Granada, Spain',
        website: 'https://puentes.seed',
        description: 'ONG dedicada a la inclusión social y laboral de personas neurodivergentes y en riesgo de exclusión.',
        diversityCommitment: 'Nuestra misión ES la inclusión. El 60% de nuestro equipo son personas neurodivergentes.',
        neurodiversityPrograms: [
            { name: 'Trabajo con Propósito', description: 'Cada puesto tiene impacto social directo y visible', type: 'culture' },
            { name: 'Flex Total', description: 'Adaptación total del puesto a la persona', type: 'accommodation' },
        ],
        subscriptionPlan: 'free',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 4, averageTimeToHire: 10 },
        jobs: [
            {
                id: 'job_ong_educador',
                title: 'Educador/a Social',
                description: 'Acompañamiento a personas en riesgo de exclusión. Empatía, comunicación y trabajo en equipo. Flexibilidad total.',
                status: 'PUBLISHED',
                skills: ['Educación social', 'Mediación', 'Intervención social', 'Dinamización', 'Trabajo social'],
                accommodations: ['flexible_schedule', 'reduced_bureaucracy', 'verbal_reports', 'meaningful_work'],
                salaryRange: '22000-30000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Horario flexible', value: 'Adapta tu jornada a tus necesidades' },
                    { name: 'Impacto social', value: 'Tu trabajo cambia vidas' },
                    { name: 'Informes verbales', value: 'Opción de dictar informes en vez de escribirlos' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Coordinador de proyectos',
                inclusivityScore: 94,
                inclusivityAnalysis: { score: 94, strengths: ['flexibility', 'meaningful_work', 'verbal_reporting', 'inclusive_culture'], improvements: [], analyzedAt: '2026-02-25T08:00:00Z' },
            },
            {
                id: 'job_ong_coordinador',
                title: 'Coordinador/a de Proyectos Sociales',
                description: 'Gestión de proyectos de inclusión laboral. Planificación, seguimiento y evaluación de programas.',
                status: 'PUBLISHED',
                skills: ['Gestión de proyectos', 'Planificación', 'Evaluación de impacto', 'Redacción de memorias', 'Subvenciones'],
                accommodations: ['structured_goals', 'written_communication', 'flexible_deadlines', 'quiet_office'],
                salaryRange: '28000-36000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Teletrabajo parcial', value: '3 días remoto, 2 presencial' },
                    { name: 'Objetivos claros', value: 'Evaluación por resultados, no por horas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Director de la fundación',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['results_based', 'flexibility', 'clear_objectives'], improvements: ['add_project_management_tools'], analyzedAt: '2026-02-25T09:00:00Z' },
            },
        ],
    },

    // ─── 10. Consultoría D&I ────────────────────────────────────
    {
        email: 'diversa.consulting@seed.diversia.com',
        name: 'Diversa Consulting',
        industry: 'Consultoría',
        size: '10-50',
        location: 'Barcelona, Spain',
        website: 'https://diversaconsulting.seed',
        description: 'Consultora especializada en diversidad e inclusión, con foco en neurodiversidad en el ámbito laboral.',
        diversityCommitment: 'Somos la prueba viva de que la neurodiversidad es una ventaja empresarial.',
        neurodiversityPrograms: [
            { name: 'Walk the Talk', description: 'Aplicamos internamente todo lo que asesoramos', type: 'culture' },
            { name: 'Flex+', description: 'Máxima flexibilidad: horario, lugar, herramientas', type: 'policy' },
        ],
        subscriptionPlan: 'pro',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 2, candidatesHired: 3, averageTimeToHire: 18 },
        jobs: [
            {
                id: 'job_diversa_consultor',
                title: 'Consultor/a de Neurodiversidad Laboral',
                description: 'Asesoramiento a empresas en adaptación de puestos, formación de equipos y políticas de inclusión.',
                status: 'PUBLISHED',
                skills: ['Consultoría D&I', 'Formación', 'Neurodiversidad', 'Accesibilidad', 'Gestión del cambio'],
                accommodations: ['flexible_schedule', 'remote_work', 'autonomy', 'reduced_admin_tasks', 'intellectual_challenge'],
                salaryRange: '35000-50000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Autonomía total', value: 'Gestiona tus proyectos a tu manera' },
                    { name: 'Impacto real', value: 'Cambias la cultura de empresas' },
                    { name: 'Formación continua', value: 'Conferencias y certificaciones pagadas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Partner responsable',
                inclusivityScore: 96,
                inclusivityAnalysis: { score: 96, strengths: ['maximum_flexibility', 'autonomy', 'meaningful_work', 'intellectual_challenge', 'walk_the_talk'], improvements: [], analyzedAt: '2026-02-26T08:00:00Z' },
            },
            {
                id: 'job_diversa_formador',
                title: 'Formador/a en Neurodiversidad',
                description: 'Diseño e impartición de formaciones sobre neurodiversidad para empresas. Creatividad y habilidades comunicativas.',
                status: 'PUBLISHED',
                skills: ['Formación', 'Diseño instruccional', 'Presentaciones', 'Neurodiversidad', 'Facilitación de grupos'],
                accommodations: ['advance_planning', 'creative_freedom', 'flexible_schedule', 'own_teaching_style'],
                salaryRange: '30000-42000 EUR',
                workMode: 'hybrid',
                visibility: 'public',
                location: 'Barcelona, Spain',
                benefits: [
                    { name: 'Libertad creativa', value: 'Diseña tus propias formaciones' },
                    { name: 'Planificación anticipada', value: 'Calendario trimestral de formaciones' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Director de formación',
                inclusivityScore: 93,
                inclusivityAnalysis: { score: 93, strengths: ['creative_freedom', 'advance_planning', 'meaningful', 'flexible'], improvements: ['add_co_facilitation_option'], analyzedAt: '2026-02-26T09:00:00Z' },
            },
        ],
    },

    // ─── 11. Construcción ──────────────────────────────────────
    {
        email: 'construcciones.verdes@seed.diversia.com',
        name: 'Construcciones Puente Verde',
        industry: 'Construcción',
        size: '50-200',
        location: 'Sevilla, Spain',
        website: 'https://puenteverde.seed',
        description: 'Constructora especializada en rehabilitación sostenible. Equipos pequeños, tareas físicas definidas y un ambiente donde cada persona aporta su ritmo.',
        diversityCommitment: 'Las manos hábiles no entienden de diagnósticos. Adaptamos las tareas al talento de cada persona.',
        neurodiversityPrograms: [
            { name: 'Obra Visual', description: 'Planos simplificados con pictogramas y códigos de color por fase de obra', type: 'accommodation' },
            { name: 'Colega de Obra', description: 'Cada nuevo trabajador tiene un compañero mentor durante 3 meses', type: 'mentoring' },
            { name: 'Zona de Regulación', description: 'Caseta habilitada para pausas sensoriales con climatización', type: 'accommodation' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 6, candidatesHired: 7, averageTimeToHire: 8 },
        jobs: [
            {
                id: 'job_construccion_peon',
                title: 'Peón de Obra',
                description: 'Apoyo general en obra: carga/descarga de materiales, limpieza de obra, preparación de mezclas. Trabajo físico sin experiencia previa necesaria. Te enseñamos todo.',
                status: 'PUBLISHED',
                skills: ['Trabajo físico', 'Carga y descarga', 'Limpieza de obra', 'Herramientas básicas', 'PRL básico'],
                accommodations: ['no_experience_required', 'physical_repetitive_work', 'buddy_system', 'visual_task_list', 'flexible_breaks', 'outdoor_work', 'clear_simple_instructions'],
                salaryRange: '16000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Sin experiencia', value: 'Formación completa desde cero' },
                    { name: 'Compañero mentor', value: 'Nunca estás solo en tu primer mes' },
                    { name: 'Carrera profesional', value: 'Posibilidad de formarte como oficial' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Oficial de obra como mentor directo',
                inclusivityScore: 84,
                inclusivityAnalysis: { score: 84, strengths: ['no_barriers_to_entry', 'physical_work', 'buddy_system', 'simple_clear_tasks'], improvements: ['add_literacy_free_instructions'], analyzedAt: '2026-02-27T07:00:00Z' },
            },
            {
                id: 'job_construccion_albanil',
                title: 'Albañil / Oficial de Obra',
                description: 'Albañilería general en rehabilitación de edificios. Trabajo físico con tareas definidas cada mañana. Equipo pequeño y ambiente comprensivo.',
                status: 'PUBLISHED',
                skills: ['Albañilería', 'Encofrado', 'Lectura de planos básicos', 'PRL Construcción', 'Herramientas manuales'],
                accommodations: ['visual_task_list', 'physical_activity', 'buddy_system', 'predictable_daily_plan', 'flexible_breaks', 'outdoor_work'],
                salaryRange: '22000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Plan de tareas visual', value: 'Cada mañana recibes pictograma con tu plan del día' },
                    { name: 'Compañero mentor', value: 'Buddy de obra durante adaptación' },
                    { name: 'Ropa y EPI incluidos', value: 'Todo el equipo proporcionado' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Jefe de obra accesible con briefing matinal visual',
                inclusivityScore: 82,
                inclusivityAnalysis: { score: 82, strengths: ['visual_plans', 'physical_work', 'buddy_system', 'outdoor'], improvements: ['add_noise_protection_options'], analyzedAt: '2026-02-27T08:00:00Z' },
            },
            {
                id: 'job_construccion_pintor',
                title: 'Pintor/a de Obra',
                description: 'Pintura interior y exterior en rehabilitaciones. Trabajo rítmico, creativo y con resultados visibles. Puedes escuchar música mientras trabajas.',
                status: 'PUBLISHED',
                skills: ['Pintura interior', 'Pintura exterior', 'Preparación de superficies', 'Mezcla de colores', 'PRL'],
                accommodations: ['music_allowed', 'own_pace', 'visual_color_guides', 'flexible_breaks', 'outdoor_work', 'movement_allowed'],
                salaryRange: '20000-28000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Música mientras trabajas', value: 'Auriculares permitidos en zonas seguras' },
                    { name: 'Resultados visibles', value: 'Ves tu progreso cada día' },
                    { name: 'Formación en color', value: 'Curso de colorimetría pagado' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de acabados con check-in diario',
                inclusivityScore: 85,
                inclusivityAnalysis: { score: 85, strengths: ['creative_element', 'own_pace', 'tangible_results', 'music_allowed'], improvements: ['add_ventilation_protocols'], analyzedAt: '2026-02-27T09:00:00Z' },
            },
            {
                id: 'job_construccion_carpintero',
                title: 'Carpintero/a de Obra',
                description: 'Carpintería en rehabilitación: puertas, ventanas, estructuras de madera. Trabajo preciso con las manos, olor a madera y resultados tangibles.',
                status: 'PUBLISHED',
                skills: ['Carpintería', 'Ebanistería básica', 'Herramientas eléctricas', 'Medición y corte', 'PRL', 'Lectura de planos'],
                accommodations: ['structured_tasks', 'visual_measurements', 'own_workspace', 'sensory_friendly_materials', 'flexible_breaks', 'tangible_results'],
                salaryRange: '24000-35000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Taller propio', value: 'Espacio de trabajo individual para concentrarte' },
                    { name: 'Materiales nobles', value: 'Trabajas con madera de calidad' },
                    { name: 'Formación continua', value: 'Cursos de ebanistería avanzada pagados' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Maestro carpintero con supervisión respetuosa',
                inclusivityScore: 87,
                inclusivityAnalysis: { score: 87, strengths: ['own_workspace', 'tangible_results', 'structured_craft', 'sensory_positive'], improvements: ['add_dust_extraction_upgrade'], analyzedAt: '2026-02-27T10:00:00Z' },
            },
            {
                id: 'job_construccion_lampista',
                title: 'Aprendiz de Lampista / Fontanero/a',
                description: 'Aprendizaje del oficio de fontanería/lampistería. Instalación y reparación de tuberías, grifería y saneamiento. Trabajo manual de precisión con agua como elemento.',
                status: 'PUBLISHED',
                skills: ['Fontanería básica', 'Soldadura de cobre', 'Herramientas manuales', 'PRL', 'Trabajo en equipo'],
                accommodations: ['apprentice_mentoring', 'visual_pipe_diagrams', 'step_by_step_learning', 'buddy_system', 'physical_activity', 'tangible_results'],
                salaryRange: '16000-22000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Aprende un oficio', value: 'Formación de lampista con maestro fontanero' },
                    { name: 'Contrato de aprendizaje', value: 'Formación remunerada desde el día 1' },
                    { name: 'Herramientas propias', value: 'Kit de herramientas a los 6 meses' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Maestro fontanero con enseñanza paso a paso',
                inclusivityScore: 83,
                inclusivityAnalysis: { score: 83, strengths: ['mentored_learning', 'visual_diagrams', 'hands_on', 'tangible_results'], improvements: ['add_literacy_support'], analyzedAt: '2026-02-27T11:00:00Z' },
            },
            {
                id: 'job_construccion_solador',
                title: 'Solador/a - Alicatador/a',
                description: 'Colocación de suelos y azulejos. Trabajo de precisión geométrica, patrones visuales y resultados inmediatos. Ideal para mentes que disfrutan con la simetría.',
                status: 'PUBLISHED',
                skills: ['Solado', 'Alicatado', 'Corte de cerámica', 'Nivelación', 'PRL', 'Geometría práctica'],
                accommodations: ['visual_pattern_guides', 'own_pace', 'systematic_work', 'tangible_results', 'minimal_social_demands', 'predictable_tasks'],
                salaryRange: '22000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Sevilla, Spain',
                benefits: [
                    { name: 'Trabajo geométrico', value: 'Patrones y simetrías: satisfacción visual garantizada' },
                    { name: 'Resultados inmediatos', value: 'Ves tu obra terminada cada día' },
                    { name: 'Autonomía', value: 'Una vez aprendido, trabajas a tu ritmo' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Encargado de acabados con revisión diaria',
                inclusivityScore: 86,
                inclusivityAnalysis: { score: 86, strengths: ['geometric_precision', 'tangible_results', 'own_pace', 'systematic_patterns'], improvements: ['add_knee_protection_upgrade'], analyzedAt: '2026-02-27T12:00:00Z' },
            },
        ],
    },

    // ─── 12. Taller Mecánico ───────────────────────────────────
    {
        email: 'taller.mecanica@seed.diversia.com',
        name: 'AutoTaller NeuroMotor',
        industry: 'Automoción',
        size: '10-50',
        location: 'Zaragoza, Spain',
        website: 'https://neuromotor.seed',
        description: 'Taller mecánico multimarca con cultura de inclusión. Valoramos el pensamiento sistemático y la atención al detalle en el diagnóstico de averías.',
        diversityCommitment: 'Los mejores mecánicos piensan diferente. La neurodiversidad nos da ventaja en diagnóstico de averías complejas.',
        neurodiversityPrograms: [
            { name: 'Diagnóstico Visual', description: 'Manuales de reparación con diagramas visuales y códigos de color', type: 'accommodation' },
            { name: 'Zona Silenciosa', description: 'Área de taller con aislamiento acústico para concentrarse', type: 'accommodation' },
            { name: 'Rutina de Taller', description: 'Cada mecánico tiene su bahía fija y horario predecible', type: 'policy' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 4, candidatesHired: 5, averageTimeToHire: 9 },
        jobs: [
            {
                id: 'job_taller_mecanico',
                title: 'Mecánico/a de Taller',
                description: 'Reparación y mantenimiento de vehículos. Diagnóstico de averías, trabajo con las manos y resolución de problemas tangibles. Bahía de trabajo propia.',
                status: 'PUBLISHED',
                skills: ['Mecánica general', 'Electricidad del automóvil', 'Diagnosis electrónica', 'Herramientas de taller', 'PRL'],
                accommodations: ['own_bay', 'visual_repair_manuals', 'predictable_routine', 'systematic_diagnosis', 'flexible_breaks', 'headphones_allowed'],
                salaryRange: '22000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Bahía propia', value: 'Tu espacio de trabajo fijo con tus herramientas' },
                    { name: 'Diagnóstico visual', value: 'Manuales con diagramas y códigos de color' },
                    { name: 'Formación marca', value: 'Cursos de especialización pagados' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Jefe de taller con asignación clara de vehículos',
                inclusivityScore: 84,
                inclusivityAnalysis: { score: 84, strengths: ['own_workspace', 'systematic_work', 'visual_manuals', 'hands_on'], improvements: ['reduce_background_noise'], analyzedAt: '2026-02-28T08:00:00Z' },
            },
            {
                id: 'job_taller_electricidad',
                title: 'Electricista de Automoción',
                description: 'Diagnóstico y reparación de sistemas eléctricos y electrónicos del vehículo. Trabajo de precisión, circuitos y lógica. Ideal para mentes analíticas.',
                status: 'PUBLISHED',
                skills: ['Electricidad automotriz', 'Diagnosis OBD', 'Cableado', 'Electrónica', 'Esquemas eléctricos'],
                accommodations: ['quiet_workspace', 'detailed_schematics', 'systematic_approach', 'minimal_interruptions', 'own_tools'],
                salaryRange: '26000-36000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Zona tranquila', value: 'Bahía de electrónica aislada del ruido' },
                    { name: 'Esquemas detallados', value: 'Acceso a bases de datos técnicas completas' },
                    { name: 'Especialización', value: 'Cursos de vehículo eléctrico e híbrido' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Responsable de electromecánica',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['quiet_area', 'systematic_logical_work', 'specialization', 'minimal_social'], improvements: ['add_visual_wiring_guides'], analyzedAt: '2026-02-28T09:00:00Z' },
            },
            {
                id: 'job_taller_aprendiz',
                title: 'Aprendiz de Mecánica',
                description: 'Aprende el oficio de mecánico/a desde cero. Cambios de aceite, filtros, neumáticos y mantenimiento básico. Un maestro mecánico te guía paso a paso.',
                status: 'PUBLISHED',
                skills: ['Mecánica básica', 'Herramientas manuales', 'Observación', 'Ganas de aprender', 'PRL básico'],
                accommodations: ['no_experience_required', 'step_by_step_mentoring', 'visual_repair_manuals', 'own_bay', 'predictable_tasks', 'buddy_system'],
                salaryRange: '14000-18000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Formación de oficio', value: 'Aprende mecánica con maestro personal' },
                    { name: 'Contrato formativo', value: 'Combinación de práctica y teoría adaptada' },
                    { name: 'Kit de herramientas', value: 'Recibes tu propio juego de herramientas' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Mecánico senior como tutor personal',
                inclusivityScore: 87,
                inclusivityAnalysis: { score: 87, strengths: ['mentored_learning', 'no_barriers_to_entry', 'visual_guides', 'hands_on', 'own_space'], improvements: ['add_theory_adaptations'], analyzedAt: '2026-02-28T10:00:00Z' },
            },
            {
                id: 'job_taller_chapa',
                title: 'Chapista / Pintor/a de Vehículos',
                description: 'Reparación de carrocería y pintura de vehículos. Trabajo artístico-manual: enderezar, lijar, imprimar, pintar. Satisfacción de ver un coche pasar de siniestrado a nuevo.',
                status: 'PUBLISHED',
                skills: ['Chapa y pintura', 'Lijado', 'Imprimación', 'Pintura a pistola', 'Colorimetría', 'PRL'],
                accommodations: ['own_booth', 'creative_precision_work', 'own_pace', 'visual_color_matching', 'music_allowed', 'tangible_before_after'],
                salaryRange: '22000-34000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Zaragoza, Spain',
                benefits: [
                    { name: 'Cabina propia', value: 'Espacio aislado para concentrarte en cada pieza' },
                    { name: 'Resultado visible', value: 'Antes y después de cada reparación: satisfacción total' },
                    { name: 'Música', value: 'Auriculares permitidos en cabina de pintura' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Jefe de chapa y pintura con revisión de calidad',
                inclusivityScore: 85,
                inclusivityAnalysis: { score: 85, strengths: ['own_space', 'creative_manual', 'tangible_results', 'music_allowed', 'precision_work'], improvements: ['upgrade_ventilation_ppe'], analyzedAt: '2026-02-28T11:00:00Z' },
            },
        ],
    },

    // ─── 13. Viveros / Agricultura ─────────────────────────────
    {
        email: 'viveros.del.sol@seed.diversia.com',
        name: 'Viveros del Sol',
        industry: 'Agricultura / Viveros',
        size: '10-50',
        location: 'Málaga, Spain',
        website: 'https://viverosdelsol.seed',
        description: 'Centro de jardinería y vivero con compromiso de inclusión laboral. El contacto con la tierra y las plantas tiene efecto terapéutico demostrado.',
        diversityCommitment: 'La naturaleza no juzga. Aquí cada persona crece a su ritmo, igual que nuestras plantas.',
        neurodiversityPrograms: [
            { name: 'Jardín Terapéutico', description: 'Zona de regulación entre plantas con banco y sombra', type: 'accommodation' },
            { name: 'Tareas Estacionales', description: 'Calendario visual de tareas por estación del año', type: 'accommodation' },
            { name: 'Sin Prisas', description: 'Ritmo de trabajo adaptado: calidad sobre velocidad', type: 'policy' },
        ],
        subscriptionPlan: 'basic',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 5, averageTimeToHire: 6 },
        jobs: [
            {
                id: 'job_vivero_jardinero',
                title: 'Jardinero/a de Vivero',
                description: 'Cuidado y mantenimiento de plantas en vivero. Riego, poda, trasplante y preparación de pedidos. Trabajo al aire libre, rítmico y con resultados vivos.',
                status: 'PUBLISHED',
                skills: ['Jardinería', 'Botánica básica', 'Riego', 'Poda', 'Trasplante', 'Identificación de plagas'],
                accommodations: ['outdoor_work', 'physical_activity', 'predictable_routine', 'visual_plant_guides', 'own_pace', 'sensory_rich_natural'],
                salaryRange: '18000-24000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Málaga, Spain',
                benefits: [
                    { name: '100% aire libre', value: 'Trabajo entre plantas y naturaleza' },
                    { name: 'Rutina estacional', value: 'Calendario visual de tareas por temporada' },
                    { name: 'Formación botánica', value: 'Aprende de plantas mientras trabajas' },
                ],
                teamSize: '3-5',
                reportingStructure: 'Encargado de vivero con briefing matinal visual',
                inclusivityScore: 90,
                inclusivityAnalysis: { score: 90, strengths: ['outdoor_natural', 'rhythmic_work', 'own_pace', 'sensory_positive', 'tangible_results'], improvements: ['add_shade_structures'], analyzedAt: '2026-03-01T08:00:00Z' },
            },
            {
                id: 'job_vivero_peon',
                title: 'Peón Agrícola / Auxiliar de Vivero',
                description: 'Apoyo general en vivero: carga, descarga, preparación de tierra, limpieza. Trabajo físico repetitivo y al aire libre. No requiere experiencia.',
                status: 'PUBLISHED',
                skills: ['Trabajo físico', 'Organización', 'Carretilla manual', 'Limpieza', 'Trabajo en equipo'],
                accommodations: ['no_experience_required', 'physical_repetitive_work', 'outdoor_work', 'visual_checklist', 'buddy_system', 'flexible_breaks'],
                salaryRange: '16000-20000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Málaga, Spain',
                benefits: [
                    { name: 'Sin experiencia previa', value: 'Te formamos desde cero' },
                    { name: 'Trabajo físico activo', value: 'Movimiento constante, nunca aburrido' },
                    { name: 'Compañero de apoyo', value: 'Buddy durante los primeros meses' },
                ],
                teamSize: '5-10',
                reportingStructure: 'Encargado de zona con instrucciones claras',
                inclusivityScore: 88,
                inclusivityAnalysis: { score: 88, strengths: ['no_barriers_to_entry', 'physical_work', 'buddy_system', 'outdoor', 'simple_tasks'], improvements: ['add_hydration_protocol'], analyzedAt: '2026-03-01T09:00:00Z' },
            },
            {
                id: 'job_vivero_florista',
                title: 'Florista / Composiciones Florales',
                description: 'Creación de ramos y composiciones florales. Trabajo artístico-manual con flores, colores y texturas. Creatividad con las manos.',
                status: 'PUBLISHED',
                skills: ['Floristería', 'Composición floral', 'Conocimiento de flores', 'Creatividad manual', 'Atención al detalle'],
                accommodations: ['creative_freedom', 'sensory_rich_positive', 'own_pace', 'quiet_workspace', 'structured_orders', 'visual_references'],
                salaryRange: '18000-26000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Málaga, Spain',
                benefits: [
                    { name: 'Trabajo artístico', value: 'Cada ramo es una obra de arte' },
                    { name: 'Entorno sensorial positivo', value: 'Aromas naturales, colores vivos' },
                    { name: 'Libertad creativa', value: 'Diseña composiciones a tu estilo' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Florista jefe con estilo libre',
                inclusivityScore: 91,
                inclusivityAnalysis: { score: 91, strengths: ['creative_manual_work', 'positive_sensory', 'own_pace', 'tangible_beautiful_results'], improvements: ['add_allergy_protocols'], analyzedAt: '2026-03-01T10:00:00Z' },
            },
        ],
    },

    // ─── 14. Artesanía / Taller de Oficios ─────────────────────
    {
        email: 'obrador.artesano@seed.diversia.com',
        name: 'Obrador Artesano Manos Diversas',
        industry: 'Artesanía',
        size: '10-50',
        location: 'Granada, Spain',
        website: 'https://manosdiversas.seed',
        description: 'Taller-obrador de artesanía (cerámica, ebanistería, restauración) que funciona como empresa social. El 70% del equipo es neurodivergente.',
        diversityCommitment: 'Las manos que crean no necesitan justificarse. Cada pieza es única, como cada persona que la hace.',
        neurodiversityPrograms: [
            { name: 'Ritmo Propio', description: 'Sin cronómetros ni presión de producción masiva. Calidad artesanal', type: 'policy' },
            { name: 'Taller Sensorial', description: 'Cada estación tiene control de luz, sonido y temperatura', type: 'accommodation' },
            { name: 'Aprendiz-Maestro', description: 'Programa de formación artesanal con mentor personal', type: 'mentoring' },
        ],
        subscriptionPlan: 'free',
        metadata: { lastLogin: new Date().toISOString(), jobsPosted: 3, candidatesHired: 6, averageTimeToHire: 7 },
        jobs: [
            {
                id: 'job_artesano_ceramista',
                title: 'Ceramista / Alfarero/a',
                description: 'Creación de piezas cerámicas a mano y torno. Trabajo meditativo, rítmico y sensorial. El barro no juzga, solo responde a tus manos.',
                status: 'PUBLISHED',
                skills: ['Cerámica', 'Torno', 'Esmaltado', 'Modelado manual', 'Hornos cerámicos'],
                accommodations: ['own_pace', 'sensory_rich_positive', 'rhythmic_repetitive', 'quiet_workshop', 'creative_freedom', 'no_time_pressure'],
                salaryRange: '18000-26000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Trabajo meditativo', value: 'El torno y el barro como regulación sensorial' },
                    { name: 'Sin presión de tiempo', value: 'Cada pieza se acaba cuando está lista' },
                    { name: 'Formación artesanal', value: 'Aprende técnicas ancestrales con maestros ceramistas' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Maestro ceramista con mentoría personalizada',
                inclusivityScore: 95,
                inclusivityAnalysis: { score: 95, strengths: ['meditative_work', 'own_pace', 'sensory_positive', 'no_time_pressure', 'creative', 'mentoring'], improvements: [], analyzedAt: '2026-03-02T08:00:00Z' },
            },
            {
                id: 'job_artesano_ebanista',
                title: 'Ebanista / Carpintero/a Artesanal',
                description: 'Creación y restauración de muebles artesanales. Trabajo de precisión con madera noble. Tu pensamiento espacial 3D es tu superpoder.',
                status: 'PUBLISHED',
                skills: ['Ebanistería', 'Restauración de muebles', 'Herramientas manuales', 'Acabados', 'Barnizado', 'Diseño de piezas'],
                accommodations: ['own_workshop_space', 'visual_blueprints', 'tangible_results', 'own_pace', 'minimal_social_demands', 'sensory_friendly_wood'],
                salaryRange: '22000-32000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Taller propio', value: 'Estación de trabajo individual equipada' },
                    { name: 'Madera noble', value: 'Trabajas con materiales de primera calidad' },
                    { name: 'Piezas con nombre', value: 'Cada mueble lleva tu firma como artesano' },
                ],
                teamSize: '2-3',
                reportingStructure: 'Maestro ebanista con supervisión respetuosa',
                inclusivityScore: 92,
                inclusivityAnalysis: { score: 92, strengths: ['own_space', 'precision_work', 'tangible_results', 'creative', 'minimal_social'], improvements: ['add_dust_extraction'], analyzedAt: '2026-03-02T09:00:00Z' },
            },
            {
                id: 'job_artesano_restaurador',
                title: 'Restaurador/a de Objetos Antiguos',
                description: 'Restauración de muebles y objetos antiguos. Paciencia, detalle y amor por recuperar la belleza de lo que otros descartan. Trabajo hiperfocal.',
                status: 'PUBLISHED',
                skills: ['Restauración', 'Historia del arte básica', 'Técnicas de envejecimiento', 'Pintura decorativa', 'Tapicería básica', 'Documentación fotográfica'],
                accommodations: ['hyperfocus_friendly', 'no_interruptions', 'own_pace', 'quiet_workshop', 'detail_oriented_tasks', 'visual_before_after'],
                salaryRange: '20000-30000 EUR',
                workMode: 'on-site',
                visibility: 'public',
                location: 'Granada, Spain',
                benefits: [
                    { name: 'Trabajo de detalle', value: 'Cada restauración es un proyecto único' },
                    { name: 'Sin interrupciones', value: 'Horario protegido de concentración' },
                    { name: 'Antes y después', value: 'Documentas tu trabajo con fotos: resultados visibles' },
                ],
                teamSize: '1-2',
                reportingStructure: 'Maestro restaurador como mentor',
                inclusivityScore: 94,
                inclusivityAnalysis: { score: 94, strengths: ['hyperfocus_ideal', 'no_interruptions', 'detail_work', 'tangible_before_after', 'own_pace'], improvements: ['add_ventilation_for_solvents'], analyzedAt: '2026-03-02T10:00:00Z' },
            },
        ],
    },
]
