// ═══════════════════════════════════════════════════════════════════
// TERAPEUTAS — 8 profesionales con especialidades complementarias
// Dominio: @seed.diversia.com (NUNCA mezclar con datos reales)
// Variados: unos para empresas, otros para individuos, mixtos
// Incluye: Terapeuta Ocupacional + Especialista EMDR/Trauma
// ═══════════════════════════════════════════════════════════════════

export const therapistProfiles = [
    // ─── 1. TDAH + Coaching ejecutivo (Empresas + Individuos) ───
    {
        email: 'carmen.vega@seed.diversia.com',
        name: 'Dra. Carmen Vega',
        specialty: 'TDAH y Coaching Ejecutivo',
        licenseNumber: 'PSI-MAD-2018-0456',
        specializations: ['TDAH', 'Coaching ejecutivo', 'Productividad neurodivergente', 'Gestión del tiempo'],
        certifications: [
            { title: 'Certified ADHD Professional', licenseNumber: 'CAHP-2022-0891', issuingBody: 'International ADHD Foundation', expiryDate: '2028-06-30' },
            { title: 'Executive Coach Certificada', licenseNumber: 'ICF-PCC-4521', issuingBody: 'International Coaching Federation', expiryDate: '2027-12-31' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-01-15T09:00:00Z' },
        neurodiversityExperience: 8,
        experienceYears: 12,
        approach: 'Coaching + CBT',
        services: ['individual_therapy', 'company_consulting', 'executive_coaching', 'workplace_adaptation', 'group_workshops'],
        languages: ['Spanish', 'English'],
        location: 'Madrid, Spain',
        bio: 'Especialista en TDAH adulto y coaching ejecutivo. Ayudo a profesionales neurodivergentes a potenciar su productividad y a empresas a crear entornos que aprovechen el talento TDAH. 12 años de experiencia con más de 300 pacientes.',
        acceptingNewClients: true,
        maxClients: 25,
        currentClients: 12,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-01-15T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: CAHP + ICF PCC. Colegiada en Madrid.',
        badges: ['neurodiversity_expert', 'verified_professional', 'company_consultant', 'top_rated'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 156,
            clientSatisfactionScore: 4.9,
            averageResponseTime: 1.5,
            lastSessionDate: '2026-03-15T17:00:00Z',
        },
    },

    // ─── 2. TEA + Integración sensorial (Individuos) ────────────
    {
        email: 'alejandro.ruiz@seed.diversia.com',
        name: 'Dr. Alejandro Ruiz',
        specialty: 'TEA e Integración Sensorial',
        licenseNumber: 'PSI-BCN-2015-1234',
        specializations: ['Autismo', 'Integración sensorial', 'Habilidades sociales', 'Regulación emocional'],
        certifications: [
            { title: 'Autism Spectrum Specialist', licenseNumber: 'ASS-2021-2345', issuingBody: 'European Autism Association', expiryDate: '2027-12-31' },
            { title: 'Terapeuta de Integración Sensorial', licenseNumber: 'TIS-2020-0567', issuingBody: 'Asociación Española de Integración Sensorial', expiryDate: '2027-06-30' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-01-20T09:00:00Z' },
        neurodiversityExperience: 11,
        experienceYears: 15,
        approach: 'Integración Sensorial + Terapia Contextual',
        services: ['individual_therapy', 'sensory_assessment', 'social_skills_training', 'family_support'],
        languages: ['Spanish', 'Catalan', 'English'],
        location: 'Barcelona, Spain',
        bio: 'Neuropsicólogo clínico especializado en TEA adulto. Mi enfoque combina la integración sensorial con habilidades sociales prácticas. Trabajo con adultos autistas que buscan adaptaciones laborales y mejora en su calidad de vida.',
        acceptingNewClients: true,
        maxClients: 20,
        currentClients: 15,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-01-20T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: ASS + TIS. Colegiado en Barcelona.',
        badges: ['neurodiversity_expert', 'verified_professional', 'sensory_specialist'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 234,
            clientSatisfactionScore: 4.7,
            averageResponseTime: 2.0,
            lastSessionDate: '2026-03-14T18:00:00Z',
        },
    },

    // ─── 3. Dislexia + Dificultades de aprendizaje (Individuos + Educación) ──
    {
        email: 'marta.soler@seed.diversia.com',
        name: 'Lda. Marta Soler',
        specialty: 'Dislexia y Dificultades de Aprendizaje',
        licenseNumber: 'LOG-VAL-2019-0789',
        specializations: ['Dislexia', 'Discalculia', 'TANV', 'Dificultades de aprendizaje', 'Tecnología asistiva'],
        certifications: [
            { title: 'Especialista en Dislexia', licenseNumber: 'DYS-2023-0123', issuingBody: 'British Dyslexia Association', expiryDate: '2028-03-31' },
            { title: 'Logopeda Colegiada', licenseNumber: 'CPLCV-2019-789', issuingBody: 'Colegio de Logopedas de la Comunitat Valenciana', expiryDate: '2027-12-31' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-02-01T09:00:00Z' },
        neurodiversityExperience: 7,
        experienceYears: 9,
        approach: 'Multisensorial + Tecnología Asistiva',
        services: ['individual_therapy', 'learning_assessment', 'assistive_technology_training', 'school_consulting', 'workplace_reading_support'],
        languages: ['Spanish', 'Valencian', 'English'],
        location: 'Valencia, Spain',
        bio: 'Logopeda especializada en dislexia y dificultades de aprendizaje en adultos. Enseño estrategias compensatorias y uso de tecnología asistiva para el ámbito laboral. También asesoro a centros educativos.',
        acceptingNewClients: true,
        maxClients: 18,
        currentClients: 10,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-02-01T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: BDA Specialist + Colegiada CPLCV.',
        badges: ['verified_professional', 'learning_specialist', 'tech_savvy'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 89,
            clientSatisfactionScore: 4.8,
            averageResponseTime: 3.0,
            lastSessionDate: '2026-03-13T16:00:00Z',
        },
    },

    // ─── 4. Neuropsicología clínica — Diagnóstico oficial (Individuos) ──
    {
        email: 'pablo.navarro@seed.diversia.com',
        name: 'Dr. Pablo Navarro',
        specialty: 'Neuropsicología Clínica — Diagnóstico',
        licenseNumber: 'PSI-ZGZ-2013-0345',
        specializations: ['Diagnóstico neuropsicológico', 'TDAH', 'TEA', 'Altas capacidades', 'Evaluación cognitiva', 'Informes periciales'],
        certifications: [
            { title: 'Neuropsicólogo Clínico', licenseNumber: 'NPC-2018-0234', issuingBody: 'Sociedad Española de Neuropsicología', expiryDate: '2028-12-31' },
            { title: 'Perito Judicial en Neuropsicología', licenseNumber: 'PJN-2020-0567', issuingBody: 'Consejo General de la Psicología de España', expiryDate: '2027-06-30' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-01-25T09:00:00Z' },
        neurodiversityExperience: 13,
        experienceYears: 18,
        approach: 'Evaluación neuropsicológica integral + Informe clínico legal',
        services: ['clinical_diagnosis', 'neuropsychological_assessment', 'expert_reports', 'second_opinion', 'capacity_assessment'],
        languages: ['Spanish', 'English', 'French'],
        location: 'Zaragoza, Spain',
        bio: 'Neuropsicólogo clínico con 18 años de experiencia. Ofrezco diagnóstico oficial y legal de TDAH, TEA, dislexia, altas capacidades y otras neurodivergencias. Mis informes tienen validez clínica y pericial para trámites laborales, educativos y judiciales.',
        acceptingNewClients: true,
        maxClients: 15,
        currentClients: 11,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-01-25T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: NPC + Perito judicial. Colegiado en Zaragoza.',
        badges: ['neurodiversity_expert', 'verified_professional', 'clinical_diagnostician', 'expert_witness'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 312,
            clientSatisfactionScore: 4.6,
            averageResponseTime: 4.0,
            lastSessionDate: '2026-03-12T11:00:00Z',
        },
    },

    // ─── 5. Coaching neurodivergente laboral (Empresas + Individuos) ──
    {
        email: 'sofia.chen.t@seed.diversia.com',
        name: 'Lda. Sofía Chen',
        specialty: 'Coaching Neurodivergente Laboral',
        licenseNumber: 'PSI-BCN-2020-0678',
        specializations: ['Coaching laboral', 'Adaptación de puestos', 'Diversidad e inclusión', 'Formación en neurodiversidad', 'Liderazgo inclusivo'],
        certifications: [
            { title: 'Neurodiversity Workplace Coach', licenseNumber: 'NWC-2023-0890', issuingBody: 'Genius Within (UK)', expiryDate: '2028-09-30' },
            { title: 'Diversidad e Inclusión Certificada', licenseNumber: 'D&I-2022-0123', issuingBody: 'Society for Human Resource Management', expiryDate: '2027-12-31' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-02-05T09:00:00Z' },
        neurodiversityExperience: 6,
        experienceYears: 8,
        approach: 'Strengths-based Coaching + Adaptación de puesto',
        services: ['company_consulting', 'individual_coaching', 'workplace_assessment', 'team_training', 'policy_review', 'onboarding_support'],
        languages: ['Spanish', 'Mandarin', 'English', 'Catalan'],
        location: 'Barcelona, Spain',
        bio: 'Coach laboral especializada en neurodiversidad. Ayudo a empresas a adaptar puestos de trabajo y formar equipos inclusivos. También acompaño a profesionales neurodivergentes en transiciones laborales y desarrollo de carrera.',
        acceptingNewClients: true,
        maxClients: 30,
        currentClients: 18,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-02-05T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: NWC + SHRM D&I. Colegiada en Barcelona.',
        badges: ['verified_professional', 'company_consultant', 'workplace_specialist', 'multilingual'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 178,
            clientSatisfactionScore: 4.85,
            averageResponseTime: 1.0,
            lastSessionDate: '2026-03-16T10:00:00Z',
        },
    },

    // ─── 6. Altas capacidades + Doble excepcionalidad (Individuos + Familias) ──
    {
        email: 'isabel.moreno@seed.diversia.com',
        name: 'Dra. Isabel Moreno',
        specialty: 'Altas Capacidades y Doble Excepcionalidad',
        licenseNumber: 'PSI-MAD-2014-0912',
        specializations: ['Altas capacidades', 'Doble excepcionalidad', 'Superdotación', 'TOC', 'Síndrome de Tourette', 'Dispraxia'],
        certifications: [
            { title: 'Especialista en Altas Capacidades', licenseNumber: 'AACC-2019-0345', issuingBody: 'European Council for High Ability', expiryDate: '2027-12-31' },
            { title: 'Psicóloga Clínica', licenseNumber: 'PIR-2018-0234', issuingBody: 'Ministerio de Sanidad', expiryDate: '2030-12-31' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-02-10T09:00:00Z' },
        neurodiversityExperience: 12,
        experienceYears: 16,
        approach: 'Terapia integrativa + Desarrollo del potencial',
        services: ['individual_therapy', 'giftedness_assessment', 'twice_exceptional_support', 'family_counseling', 'career_guidance'],
        languages: ['Spanish', 'English', 'Italian'],
        location: 'Madrid, Spain',
        bio: 'Psicóloga clínica especializada en altas capacidades y doble excepcionalidad (superdotación + otra neurodivergencia). Trabajo con adultos que descubren tarde sus altas capacidades y con perfiles complejos como AACC+TDAH, AACC+TOC o AACC+Tourette.',
        acceptingNewClients: true,
        maxClients: 20,
        currentClients: 14,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-02-10T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: ECHA + PIR. Colegiada en Madrid.',
        badges: ['neurodiversity_expert', 'verified_professional', 'giftedness_specialist', 'clinical_psychologist'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 267,
            clientSatisfactionScore: 4.75,
            averageResponseTime: 2.5,
            lastSessionDate: '2026-03-14T19:00:00Z',
        },
    },

    // ─── 7. Terapeuta Ocupacional — Adaptación de oficios manuales ──
    {
        email: 'lucia.ramos@seed.diversia.com',
        name: 'Lda. Lucía Ramos',
        specialty: 'Terapia Ocupacional para Neurodiversidad en Oficios Manuales',
        licenseNumber: 'TO-AND-2020-0234',
        specializations: ['Terapia ocupacional', 'Adaptación de puestos manuales', 'Ergonomía neurodivergente', 'Integración sensorial en oficios', 'Capacitación laboral'],
        certifications: [
            { title: 'Terapeuta Ocupacional Colegiada', licenseNumber: 'COTO-AND-2020-0234', issuingBody: 'Colegio de Terapeutas Ocupacionales de Andalucía', expiryDate: '2028-12-31' },
            { title: 'Especialista en Integración Sensorial (Ayres)', licenseNumber: 'SI-2023-0189', issuingBody: 'University of Southern California / Asociación Española de IS', expiryDate: '2029-06-30' },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-02-20T09:00:00Z' },
        neurodiversityExperience: 6,
        experienceYears: 8,
        approach: 'Terapia Ocupacional basada en fortalezas + Integración Sensorial',
        services: ['workplace_assessment', 'manual_job_adaptation', 'sensory_integration_therapy', 'ergonomic_consulting', 'company_training', 'individual_therapy'],
        languages: ['Spanish', 'English'],
        location: 'Sevilla, Spain',
        bio: 'Terapeuta ocupacional especializada en adaptar oficios manuales (construcción, mecánica, jardinería, hostelería) a perfiles neurodivergentes. Mi trabajo es hacer que el puesto se adapte a la persona, no al revés. Evalúo in situ en talleres, obras y cocinas.',
        acceptingNewClients: true,
        maxClients: 22,
        currentClients: 14,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-02-20T10:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: COTO Andalucía + certificación SI Ayres. Colegiada.',
        badges: ['neurodiversity_expert', 'verified_professional', 'occupational_therapist', 'manual_trades_specialist'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 189,
            clientSatisfactionScore: 4.8,
            averageResponseTime: 3,
            lastSessionDate: '2026-03-13T11:00:00Z',
        },
    },

    // ─── 8. EMDR / Trauma — Neurodivergentes con trauma laboral ──
    {
        email: 'rafael.torres@seed.diversia.com',
        name: 'Dr. Rafael Torres',
        specialty: 'EMDR y Trauma en Personas Neurodivergentes',
        licenseNumber: 'PSI-VAL-2015-0789',
        specializations: ['EMDR', 'Trauma laboral', 'Burnout neurodivergente', 'Ansiedad', 'Trastorno bipolar', 'Regulación emocional'],
        certifications: [
            { title: 'EMDR Europe Practitioner', licenseNumber: 'EMDR-EU-2019-1234', issuingBody: 'EMDR Europe Association', expiryDate: '2028-03-31' },
            { title: 'Psicólogo Clínico (PIR)', licenseNumber: 'PIR-2018-VAL-456', issuingBody: 'Ministerio de Sanidad', expiryDate: null },
        ],
        certificationValidation: { validated: true, checkedAt: '2026-02-22T14:00:00Z' },
        neurodiversityExperience: 9,
        experienceYears: 14,
        approach: 'EMDR + Terapia de Aceptación y Compromiso (ACT)',
        services: ['individual_therapy', 'trauma_processing', 'burnout_recovery', 'anxiety_management', 'bipolar_support', 'emotional_regulation'],
        languages: ['Spanish', 'English', 'French'],
        location: 'Valencia, Spain',
        bio: 'Psicólogo clínico especializado en trauma y EMDR con personas neurodivergentes. Muchos de mis pacientes han sufrido bullying, exclusión laboral o burnout. Trabajo el trauma que deja una vida de ser "diferente" en un mundo que no se adapta. Especial experiencia con bipolaridad, ansiedad y perfiles complejos.',
        acceptingNewClients: true,
        maxClients: 18,
        currentClients: 12,
        verificationStatus: 'verified',
        verifiedAt: new Date('2026-02-22T15:00:00Z'),
        verifiedBy: 'admin_system',
        verificationNotes: 'Credenciales verificadas: EMDR Europe + PIR. Colegiado en Valencia.',
        badges: ['neurodiversity_expert', 'verified_professional', 'trauma_specialist', 'clinical_psychologist'],
        metadata: {
            lastLogin: new Date().toISOString(),
            sessionsCompleted: 312,
            clientSatisfactionScore: 4.9,
            averageResponseTime: 2,
            lastSessionDate: '2026-03-15T18:00:00Z',
        },
    },
]
